- sites.json
There's no URL, because there are no relevant help articles, or *anything*. There's not even an account page or anything alike, it's all inside the mobile app.
> Add Facebook Messenger

- sites.json
Currently the old page cannot be found and return a 404 page. So I updated it to the page where you can directly press the button in order to delete the account.
> Fix codecademy delete link

- package.json
`gulp-ga` is not listed in the package dependencies but it is required to run the gulp tasks. I also added the name and version because they were missing. Assumed version 1.0.0 since this is a fork of an already in-production project.
> Correct issues with package.json

- sites.json
HTML escape sequences (such as `&rarr;` and `&lsquo;`) do not render as their intended HTML entities when printed to the page; they instead render unaltered. This commit replaces them with their actual Unicode characters.
> Remove HTML escape sequences

- sites.json
Retroactively applies .editorconfig
(I think this whitespace existed before `.editorconfig` did?)
> Remove trailing whitespace

- sites.json
~last.fm now provides a simple "Close account" button in its profile settings page.~
last.fm evidently retains your account information indefinitely.
> Update last.fm in sites.json

- docs/assets/js/scripts.js
In Firefox, the document overflow is placed at the `<html>` level, so the tag must be included in `scrollTo()` invocations.
Ref: http://stackoverflow.com/a/8149216/540162
Fixes jdm-contrib/justdelete.me#68
> Fix FireFox scrollTo bug

- sites.json
The account deletion info were moved from https://ello.co/delete-account to https://ello.co/wtf/help/settings/. The former page also does no longer exists.
Also the info text changed a bit. Additionally I updated the German translation.
> Fix ello.co link

- sites.json
There's no official explanation but contacts available for other account-related reason.
You can find various denial of account removal request on the official forum.
> Add osu.ppy.sh

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Hitbox.tv redirects to Smashcast.tv as it was merged with Azubu [1],
thus this commit removes the now-outdated account deletion steps for
Hitbox.tv, and adds the steps required to delete an account from
Smashcast.tv.
[1]: https://en.wikipedia.org/wiki/Smashcast.tv#firstHeading
> Remove Hitbox, add Smashcast to sites.json

- sites.json
Quora no longer require users to email support regarding account deletion. They have provided a 'delete' link.
> Updated quora. Set difficulty to easy

- docs/assets/js/scripts.js
This improves search to allow searching for domains in addition to site names.
For example, searching for `amazon.com` would show both Amazon and AWS, and searching `angel.co` would show Angelist.
> Expand search to site URLs

- _data/sites.json
Wasn't sure whether the URL should be this page instead:
https://greenmangaming.zendesk.com/hc/en-us/articles/360006712732-Account-Deletion-Deactivation-FAQ
It dosn't actually explain *how* to delete your account, whereas the privacy policy does have that information quite clearly under "Data Handling and Your Choices".
> Add Green Man Gaming

- assets/js/scripts.js
For whatever reason, adding the `autofocus` attribute to the search field's HTML tag didn't do the trick. Thankfully, it's a one-line Javascript fix to get that to work properly.
Closes jdm-contrib/jdm#276
> Auto-focus search field on page load

- _data/sites.json
So the website's language setting won't be overwritten
> Remove language parameter from entry

- _data/sites.json
This PR updates the EasyJet contact link to be a more specific link for requesting account deletion. 
https://www.easyjet.com/en/policy/privacy-promise/request-data-form
This saves people an extra hop of finding that link, which I received after starting a live chat.
> Add more specific link for EasyJet account deletion request

- _data/sites.json
_Changes_
* Updated: `url`, `difficulty`, `notes` and `notes_pt_br` from Coinbase account deletion info.
* Updated: `url`, `notes`, `notes_pt_br` and `domains` from Bitly account deletion info.
* Added: 000Webhost account deletion info.
* Added: CoinBR/Stratum account deletion info.
* Added: Happy Scribe account deletion info.
_Additional information_
"**CoinBR**" is now called as "**Stratum**". `coinbr.io`, `coinbr.net` and `stratum.hk` are domains owned by the same company. They also are related to the same type of account.
I have modified the level of difficulty of the **Coinbase** account deletion from `easy` to `medium` because Coinbase only allows an account to be permanently deleted if there is no pending transaction or some limitation applied to them, In this case, it may be …
> Account deletion at Stratum.hk and 000Webhost.com

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
Just upgrading dependencies to newer versions.
Not upgrading to Jekyll 4.0 because it fails. Issue already reported here:
https://github.com/jekyll/jekyll-sass-converter/issues/93
> Upgrade dependencies

- _data/sites.json
This pull request adds entries for the following services:
- Acasa (helloacasa.com)
- Bring! (getbring.com)
- Guild Wars / ArenaNet (guildwars2.com)
- iStudiez (istudentpro.com)
- MacTrade (mactrade.de)
- MacUpdate (macupdate.com)
- Mapstr (mapstr.com)
- MyFRITZ! (myfritz.net)
- Ninox (ninoxdb.de)
- Passdock (passdock.com)
- Philips Hue (meethue.com)
- Pixabay (pixabay.com)
- Taiga (taiga.io)
- United Domains (united-domains.de)
- Things (culturedcode.com)
- Pixum (pixum.com)
- Doodle (doodle.com)
- Koingo Software (koingosw.com)
- Outdooractive (outdooractive.com)
- Inoreader (inoreader.com)
It also fixes the entries for the following services:
- Overleaf (Accounts can now be deleted without contacting support)
- Feedly (Accounts can be deleted without contacting support)
> Add 20 Sites, Fix Overleaf & Feedly

- _data/sites.json
- script/cibuild
- script/ping_websites.rb
- script/validate_json.rb
This is a first attempt to ensure that we always have valid links on our JSON. I have divided it into several commits as I was cleaning up the JSON. 
- Most of them are related to websites that really ceased to exist
- Some are fixing broken links on existing websites
- Some are fixes to the URL format in JSON or adding URLS to entries without ones
- Then there is the commit itself.
I didn't make it error out just like the other, because I still have to figure out two things:
- Links to restricted sections of a website that is still valid, which require login and thus returns 404
- Some websites (actually just `premera.com`) spuriously timing out.
> Add script to check for websites validity

- _data/sites.json
It ceased operating in [December, 2018](http://en.wikipedia.org/wiki/Linux_Counter) and stopped responding in [October 2019](https://travis-ci.org/jdm-contrib/jdm/builds/597252011)
> Remove Linux Counter

- _data/sites.json
I have not found a support page explaining how to delete an account, only reddit comments such as [this comment](https://www.reddit.com/r/gfycat/comments/bvxsal/how_do_you_delete_a_gfycat_account/eptawui/) going back several years.
The support page I added as url does not have any relevant info other than the support email.
> Added Gfycat

- _data/sites.json
Update the following websites that are currently marked as impossible, as they have added methods to delete accounts:
* Backblaze: It is possible to delete Backblaze accounts with a link in the account settings, but the accounts contents must be deleted first.
* eDreams: Has a button to delete account in the settings with immediate effect. 
* last.fm: The wording on the setting page now seems to indicate that the account data will be permanently deleted after 14 days.
> Update websites with improved difficulty

- _data/sites.json
As of Build [#968](https://travis-ci.org/jdm-contrib/jdm/builds/600362808), Gitorious seems to be offline. It has been just a read only website for some time, but they might have decided to shut it down.
Since it's owned by GitLab, which is fairly big, I'll give it a 2-3 day grace period to see if it comes back online, before merging.
> Remove Gitorious

- _data/sites.json
Has been consistently offline since build #974, on October 22.
[Twitter](https://twitter.com/mylifecom) shows no activity since 2016
[Facebook](https://www.facebook.com/MyLifeUS/) has a post from October 21, but none of the links to the company work.
I'll give it a couple days, then delete it.
> Remove MyLife.com

- _data/sites.json
Update the following sites to hard:
- Netflix: The support page indicates that accounts are now automatically deleted 10 months after membership cancellation or upon request to support.
- Geocaching: The support page seems to indicate that by contacting support, it is possible to request permanent account deletion.
> Update Netflix and Geocaching to hard

- _data/sites.json
There is an account deletion page for OpenDNS. This commit includes the direct link there.
> Fix OpenDNS Deletion process

- script/ping_websites.rb
This will prevent CI failures like this one:
https://travis-ci.org/jdm-contrib/jdm/builds/627660808
> Catch EOFError in website ping script

- _data/sites.json
The [latest builds](https://travis-ci.org/jdm-contrib/jdm/builds/638907045?utm_source=github_status&utm_medium=notification) on Travis started erroring out on Stereomood. It turns out that it seems like they haven't been run by their owners since 2015 ([1](https://medium.com/@stereomoodteam/the-last-song-for-stereomood-s-founders-b9c2b2ac0cf0), [2](https://www.facebook.com/photo.php?fbid=10207162736486323&set=o.50644269128&type=3&theater), [3](https://twitter.com/stereomood?lang=en)). Maybe just the domain was still up.
In any case, I'm removing it.
> Remove Stereomood

- _data/sites.json
Kit.com [started failing](https://travis-ci.org/jdm-contrib/jdm/builds/644746011?utm_source=github_status&utm_medium=notification) and I found out it's because they [switched their domain to kit.co](https://domainnamewire.com/2019/11/25/kit-com-is-losing-its-domain-name-switching-to-kit-co/)
> Update kit.com to kit.co

- CONTRIBUTING.md
- _data/sites.json
- script/validate_json.rb
This PR introduces lots of changes to `validate_json.rb`:
- Enumerated `ErrorCodes` for each exit code it uses.
- Enforce that `difficulty` and `domains` are always filled.
- Enforce that `difficulty` is always one of `easy`, `medium`, `hard`, `impossible`
It also fixes:
- `validate_json.rb` not linting first entry
- Several entries not having any `domains` filled
> Make validate_json script stricter

- .travis.yml
- script/check_files_formatting.sh
- script/cibuild
- script/run_jekyll.sh
~This is a workflow that will eventually replace Travis, so that we get GH's native CI capabilities and thus have faster (maybe?) and cleaner or more accessible results.~
Turns out we can do a lot better on Travis than in GH actions flow, so instead I just opted to continue using it.
- We now use `bundler` cache, which completely eliminates our need to install everything from scratch.
- I've separated each step in the `cibuild` script into a different script which it calls. `cibuild` is still there for developers on offline use.
- The step above allows us to run all of the linting steps in parallel. Each step takes roughly 1min, this means that the job can finish in 1min (best case scenario) vs 4min in the past. It also makes it more clear to the authors of the PRs which of the steps is …
> Speed up Travis CI and improve error reports

- _data/sites.json
I didn't handle redirections, because of lacking accounts on all resources :earth_americas:
`www` was removed as redundant where it is possible.
But it was pasted where resource redirects from `domain.com` to `www.domain.com` for 2 ms speedup :ok_hand: 
`http:`-domains that survived after this commit are blocked in my country (**linkedin** and **dailymotion** [**plz, check them**. Maybe they also serve TLS?]) _or_ redirects to login page _or_ died at all.
> HTTP replaced to HTTPS where it is available

- script/validate_json.rb
This makes sure that whenever someone translates it to a new language, or touches any of the language files, all of the keys remain sane and that it has no more or no less than the exact keys that are expected.
> Validate site translation files

- _data/sites.json
Failed to respond on job [#685031436][1]
[Wikipedia states][2] that it closed on May 25, 2018
[1]: https://travis-ci.org/github/jdm-contrib/jdm/jobs/685031436
[2]: https://en.wikipedia.org/wiki/Klout
> Remove entry for 'Klout'

- _data/sites.json
These URLs were failing for several days, so I created an account with a disposable mail and confirmed they really don`t work anymore.
There's no delete button on the profile section and no mention on how to delete in the FAQs, I`m assuming mailing customer support will do it, because I got a reply but couldn't see what it was because the disposable e-mail failed me 🗡️
> Update Buycraft & Tebex difficulty to hard

- _data/sites.json
Hi, 
We recently implemented self-service account deletion for all ecloud.global users.
It can be seen with screenshots at the same URL we documented the previous procedure based on email.
This is the step previous to deletion (some style improvements needed 😛 ):
We no longer accept the email based flow. Besides, it was filling our community forum with random "Please delete my account, my username is XXXXXX" messages from users who don't even have an account there. I don't know if users willingly sent those messages or if there is some automated tool that is firing unsubscribe requests for all sites declared in JDM.
We are using an [open source plugin for Nextcloud](https://framagit.org/framasoft/nextcloud/drop_account), to which we're contributing.
> Update the procedure to delete an /e/ account in ecloud.global

- _data/sites.json
- [Their website](https://cheddarapp.com/account) doesn't load anymore
- The ping has been failing from [Travis #1421](https://travis-ci.org/github/jdm-contrib/jdm/jobs/688558269) to [Travis #1442](https://travis-ci.org/github/jdm-contrib/jdm/jobs/692861023)
- [Twitter](https://twitter.com/cheddarapp?lang=en) is inactive since July 3, 2019
- [Wayback Machine shows](https://web.archive.org/web/20180626035424/https://cheddarapp.com/changelog) latest change was on 2017
> Remove Cheddar App

- _data/sites.json
According to their [Twitter](https://twitter.com/foodspotting?lang=en), it's been discontinued since May, 2018
Ping has started failing on [Travis #1441](https://travis-ci.org/github/jdm-contrib/jdm/jobs/692860984)
> Remove Foodspotting

- CONTRIBUTING.md
- Removed the very specific Spanish section on `CONTRIBUTING`. We don't have activity enough to justify it.
- Improved `CONTRIBUTING` to state all steps necessary to make a new translation visible.
> Improve translation instructions

- CONTRIBUTING.md
- TRANSLATION_REFERENCE.md
- Disambiguate when the translation already exists
- Add a document explaining how each of the translatable strings is used, to help translators find their way around without having to understand the HTML
> Fix #536: Add details on translation keys

- _data/sites.json
This commit adds Pexels to the sites.json list, with a URL to a help article provided by Pexels. I have set the difficulty to medium as there may be *some* instances where you need to contact a human to delete your account, however, it is unlikely.
> Pexels Integration

- _data/sites.json
`Krrb` has been failing to answer to pings since [#1456.3](https://travis-ci.org/github/jdm-contrib/jdm/jobs/694709047), two weeks ago.
I haven't found any other reference, but I figured 2 weeks was enough time to get a website back online
> Remove Krrb

- .travis.yml
- README.md
`nokogiri` still can't handle Ruby 2.7
> Fall back to RVM 2.6.6

- assets/js/scripts.js
We were really getting the second letter and I don't know for how long this has been a bug hahaha
> Fix #554: initial character sorting skipps first letter

- _data/sites.json
Started failing around Travis' job 1551: https://travis-ci.org/github/jdm-contrib/jdm/jobs/704749746
Twitter is inactive since 2015, wayback machine can't provide a rendering so I can see when it started to fail, but I'm removing it anyway
> Remove Lumi

- _data/sites.json
According to the [wayback machine](https://web.archive.org/web/20171201195748/https://beam.pro/), Beam has been redirecting to mixer for a while and [Mixer](https://mixer.com/) has shut down as of July 22nd: 
(Found out while investigating [this job](https://travis-ci.org/github/jdm-contrib/jdm/jobs/711707331))
> Remove Beam

- _data/sites.json
- The website is offline
- I can't seem to find any digital presence from them anymore
- The links to their social media on the internet archive don't work
- The app has vanished from Play store
All of this leads me to believe that it's gone, so I'm removing it.
> Remove Whistle.im

- _data/sites.json
Their [latest tweet](https://twitter.com/desktopprapp?lang=en) is from 2015 and is selling the website. Don't know why it took so long to pop-up on the script, maybe someone bought and gave up
> Remove Desktoppr

- _data/sites.json
Page with the account closure button has changed.
As this is JDM, I was unsure whether these instruction should be changed to say you can request deletion of all held personal data from https://www.coinbase.com/settings/privacy-rights which will then direct you to close your account too.
Or does the project scope stop at deletion of account only?
> Update Coinbase link

- _data/sites.json
Unfortunately disabling your account does not delete it. Ever. Not even after a period of inactivity. If you ever show up on change.org again they will reactivate your account for you to use.
> It's actually impossible to delete a change.org account

- _data/sites.json
Service has shut down on Jan 1, 2020
https://slimtimer.wordpress.com/2019/11/17/slimtimer-shutting-down-on-dec-15-2019/
> Remove SlimTimer

- _data/sites.json
Support doc: https://support.turo.com/hc/en-us/articles/203991030-How-to-close-your-account
Directly linking to the account close doesn't work, so I liked to the previous page and instructed user to click button to delete account.
> Added Turo.com

- _data/sites.json
> DEV.to now has a delete account button

- _data/sites.json
Wunderlist has shut down and has been replaced by Microsoft To Do.
The site was shut down on November 15, 2020.
> Remove Wunderlist

- _data/sites.json
Seems like BBC iD is not working at all anymore, even the base link returns 404. This might have been merged into "BBC Account", but I can't confirm.
Wayback machine link points to something with a huge deprecation notice: https://web.archive.org/web/20200123100702/http://www.bbc.co.uk/frameworks/id/gettingstarted
> / Remove BBC iD

- _data/sites.json
Added the "closemyaccount@chegg.com" email for Chegg.com. This is the direct contact email for contacting Chegg about deleting your account.
> Add email for Chegg.com

- _data/sites.json
This is failing to respond on the ping script. According to [Wikipedia](https://en.wikipedia.org/wiki/Smashcast) it was shutdown on november 2020:
> According to the Wayback Machine, smashcast.tv last successfully loaded on November 16th, 2020, and failed to load on all attempts after November 28th, 2020.
> Remove Smashcast

- _data/sites.json
Since there are no anchors to the section about account deletion, I've used a feature available for chromium-based browsers. Visiting [the URL](https://www.keepersecurity.com/privacypolicy.html?t=v#:~:text=You%20may%20deactivate%20your%20Keeper%20Security%20account%20and%20delete%20your%20personally%20identifiable%20information%20at%20any%20time%20by%20contacting%20us%20at%20support%40keepersecurity.com%20clearly%20indicating%20that%20you%20wish%20to%20deactivate%20and%20delete%20such%20information.) will highlight the part about requesting account deletion. In other browsers, you'll simply just land on the top of the page, as normal.
> Add Keeper Security

- _data/sites.json
Desk.com is now part of salesforce and doesn't have its own website
According to [this article](https://help-desk-migration.com/desk-com-soon-to-close-why-alternatives-and-how-to-migrate/) and its [twitter](https://twitter.com/desk) it has closed since march 2020.
> Remove Desk.com

- _data/sites.json
The previous URL no longer works, and this one takes the user directly to the account deactivation page. As far as I can tell, the notes are still applicable.
> Update kik URL to delete/deactivation page

- _data/sites.json
Bring! now supports deleting accounts by opening a special link in the Bring! app.
Reference: https://www.getbring.com/help-center-main-categories/profile-settings
> Update delete instructions for Bring!

- _data/sites.json
After mailing eurepresentative@reddit.com, you get a generic response:
The link is generic, mailto:-like, what prefills some fields on sending a message to reddit, so why not give it to the user right away.
Since Reddit only claims to comply with actual GDPR-backed requests, I'd say it's better to make a separate entry for it.
> Reddit: Add info for GDPR-enabled accounts.

- _data/sites.json
Using Text Fragments in URL can point the link directly to desired section on a page and highlights the text.
Example for the proposed change:
More info about Text Fragments: https://web.dev/text-fragments/
> GitHub link points to delete section

- _data/sites.json
An interesting one, unclear if these are seperate accounts or one under
different names, but the support form provides a way to request deletion
of both.
Included the GDPR approach as it's significantly easier for those who can use it.
> Add Glyph / Trion Worlds / Gamigo

- _data/sites.json
Added information on how to disable/sanitize a Target.com account. These account cannot be deleted, but they can be closed almost immediately after talking with a support rep.
I don't know that my note about using a temporary email address is strictly necessary. However, since a potential snooper with someone's Target account email address and full name can just call Target and reenable the account, later to obtain the password etc., someone might find this advice useful.
> Add Target

- _data/sites.json
This took a while to find.
LeetCode's [Privacy Policy](https://leetcode.com/privacy/) is unhelpful, and their relevant [support article](https://support.leetcode.com/hc/en-us/articles/360014821014-How-can-I-delete-my-account-) does not specify how to "submit a request to [LeetCode's] support team." After some research, I found the link to their Support Request form in [a comment](https://leetcode.com/discuss/feedback/803485/How-to-permanently-delete-leetcode-account/665594) on [a LeetCode Discuss forum post](https://leetcode.com/discuss/feedback/803485/How-to-permanently-delete-leetcode-account). After that, following the instructions in the aforementioned support article actually worked!
I don't know how to translate these notes into Turkish, nor exactly what that URL looks like, but …
> Add account deletion instructions for LeetCode

- _data/sites.json
For the `url` I added https://redirect.invidious.io/preferences, this provides a list of instances they can press and go to the sites prefs (see image below), since there's so much instances.
> Add Invidious

- _data/sites.json
Don't know what to put in `url` because there's nothing in the FAQ saying about account deletion but I'm 99.999% sure you can't delete it.
On the [account page](https://support.hotspotshield.com/hc/en-us/articles/204600084-What-can-I-see-from-my-Hotspot-Shield-account-page-) there's no delete account page)
I tried contacting support but that requires payment (you need to buy a subscription to get support, FAQ is for free users only)
I tried searching things on the FAQ such as [`delete`](https://support.hotspotshield.com/hc/en-us/search?commit=Search&page=1&query=delete&utf8=%E2%9C%93#results) then `deletion` and got this: [What is a Premium Family plan-and how does it work](https://support.hotspotshield.com/hc/en-us/articles/360045835311-What-is-a-Premium-Family-plan-and-how-does-it-work-) …
> Add Hotspot Shield

- _data/sites.json
This one's a journey.
PTC appears to own Chalk, since the in-app links redirect there. [PTC's Privacy Policy](https://www.ptc.com/en/documents/policies/privacy) states that personal information may be deleted upon request. (The same policy [points users to Vuforia Chalk's privacy policy](https://www.ptc.com/en/documents/policies/privacy#2), but the provided URL redirects to PTC's own policy.) [The relevant Help article](https://support.ptc.com/help/vuforia/chalk_app_center/#page/Vuforia_Chalk_Admin_Center%2Fcommon%2Fget_help.html%23) offers an email address to contact Vuforia support: vuforia-support@ptc.com. That address bounces mail back, and apparently does not exist anymore.
EDIT: PTC provides a [means of contacting a sales representative](https://www.ptc.com/en/contact-us), which …
> Vuforia Chalk

- _data/sites.json
I'm unsure what to do here. Their [Privacy Policy](https://www.officedepot.com/cm/help/privacy-statement) lays out a process for deleting one's own account, but after trying that process twice, my account remained fully intact.
A support representative claimed at first that there is no account deletion process. When I quoted the Privacy Policy on the matter and requested clarification, they said that they could indeed delete the account information and close the account, but the user's name and account number would remain. They kindly closed my account then, at my request, and my login credentials _finally_ no longer work.
@tupaschoal Given that Office Depot's account deletion procedure, as laid out in their Privacy Policy, does not function but might in the future, should I describe that …
> Add Office Depot

- .github/workflows/workflow.yml
I had tried changing the workflow to the GH Actions before, on #467. At the time, it was not able to match the performance of Travis, and thus I just worked on ironing out the Travis CI setup and improving it.
A lot has changed since then: 
- GH actions have matured and evolved tremendously
- Travis-CI became paid after you run out of their credits and 
We need to switch to GH actions to maintain our ability to always run the checks for free. Other than that, it has also become significantly faster than Travis, which is a great win, as shown on the table below.
Step|Travis|GH Workflow|
------------|---------- |--------
Run Jekyll Tests|47s|14s
Validate JSON|37s|11s
Ping Websites|173s|141s
Check Files Formatting|39s|11s
All things considered, I'm enabling GH Actions immediately and will …
> Implement alternative CI on GitHub Actions

- _data/sites.json
Original Zendesk page has been shutdown, but seems like it still isn't possible to delete account, so linking to the archive.
https://opposite-lock.com/topic/627/so-is-there-a-way-to-delete-my-kinja-account/11
> Update all Gawker Media websites links to internet archive

- _data/sites.json
Site was shut down according to what seems to be the founder: 
https://forum.sudobox.io/t/plexguide-pgblitz-plex-one-redirect/96
> Remove PlexGuide

- _data/sites.json
Twitter inactive since 2019: https://twitter.com/cryptfolio
Facebook inactive since 2018: https://www.facebook.com/cryptfolio
Wayback machine stopped crawling it in Feb 2021: https://web.archive.org/web/20210115000000*/https://cryptfolio.com/
> Remove CryptFolio

- TRANSLATION_REFERENCE.md
- _data/trans/ar.json
- _data/trans/cat.json
- _data/trans/cz.json
- _data/trans/de.json
- _data/trans/en.json
- _data/trans/es.json
- _data/trans/fa.json
- _data/trans/fr.json
- _data/trans/gr.json
- _data/trans/id.json
- _data/trans/it.json
- _data/trans/kr.json
- _data/trans/nl.json
- _data/trans/pl.json
- _data/trans/pt_br.json
- _data/trans/ro.json
- _data/trans/ru.json
- _data/trans/sk.json
- _data/trans/sr.json
- _data/trans/th.json
- _data/trans/tr.json
- _data/trans/vi.json
- _data/trans/zh-cn.json
- _data/trans/zh-tw.json
- _includes/body.html
- script/validate_json.rb
* When no note is provided and an email address is provided, display a default note.
* When no note is provided and the difficulty is "easy", display a (different) default note.
I'm not sure if the "url" field is required. If it is, I suspect that the vast majority of "easy" entries provide a direct URL to the account/information deletion place.
Closes #653
> Add default notes for when a deletion procedure is clear

- _data/sites.json
I thought of setting the difficulty to impossible considering CVS Pharmacy doesn't provide a legitimate way for non-California residents to delete their account, but since it is currently possible for anyone to just input a California ZIP code in the account deletion form,  I set it to medium difficulty.
The Artist Union shut down on August 1st, 2020 and it is no longer possible to log into accounts to delete them, so I've removed it's listing.
> Add CVS Pharmacy, remove The Artist Union

- _data/sites.json
- Updated CloudApp's difficulty, URL, note and added a new domain. I would link to their support page on deleting an account, but the instructions they list actually show how to delete data from a workspace instead of the full account.
- Updated Osu!'s difficulty and URL. Added an email and note.
- Updated Edpuzzle's difficulty, URL, and note. Removed Turkish note translation.
- Updated Barnes & Noble's difficulty, URL, and note. Removed Turkish note translation.
- Updated botlist.space's name to discordlist.space, and updated the URL to point directly to their Discord server, as the old URL showed 404 Not Found.
- Updated IRCCloud's URL and note. The URL now goes directly to the settings page containing the button to delete the account. Removed Turkish note translation.
- Updated Sedo's …
> Updated 8 sites, removed 2

- .gitignore
- _includes/body.html
- _includes/header.html
- assets/css/style.css
By adding `position: fixed;` to the language dropdown and instructing the plugin to use absolute position coordinates, we can place it at the same location it would otherwise have been placed at before.
To account for the possibility that a user has a screen small enough that they cannot view the full list of items, I've added scrolling overflow to this dropdown.
Fixes #987
> Fix language dropdown position drifting on page scroll

- _data/sites.json
- Updated Barnes & Noble's URL.
- I forgot to change the link when I last updated it's notes. 
- Updated Font Awesome's URL and notes. Removed it's email, as emailing is no longer necessary.
- Updated Change.org's URL, difficulty, notes, and added an email address.
- Change.org does have a web form to submit deletion requests through, but it is currently not working properly. I contacted their support and they confirmed they do also accept account deletion requests sent to help@change.org.
- Updated Channel 4's URL, notes, and removed notes translation.
- Updated NoIP's URL, notes, and removed notes translations.
- Updated Bitly's URL, notes, and removed notes translations.
- Updated Airbnb's URL, difficulty, notes, and notes translations.
- Updated Aliexpress's URL, notes, and removed …
> Updated 14, added 6, removed 3 sites

- _data/sites.json
The deletion process has changed and no longer requires one to send an
email to MongoDB's support team to delete your account. It can be done
from the site's settings page. Thus I've updated the difficulty and the
notes.
I've also changed the name from "Mongo Atlas" to "MongoDB Atlas" because
that's the name of the service according to their website.
> Update instructions for MongoDB Atlas

- _data/sites.json
- Added Packagist
- Added Progate
- Added Thingiverse
- I'm unable to provide a direct URL to Thingiverse's 'Account Settings' page since the URL contains the username of the logged in user.
- Added CoinMarketCap
- When asked about account deletion, they said the feature is still being worked on, but it's possible to have your account deleted by contacting support. [Screenshot](https://user-images.githubusercontent.com/26071735/143529907-527ea1e5-62f0-493a-a160-49a432d560cf.png)
- Added Baby Names
- Added Anime-Planet
- Updated Supercell's URL, added an email and replaced a domain.
- Updated StatusCake's URL and notes.
- Updated CafePress's URL, difficulty, notes, and removed notes translations.
- Updated 500px's URL, difficulty, and notes.
- Removed Soup.io
- Soup.io, the Austrian social …
> Added 6, removed 1, updated 4 entries

- assets/css/style.css
Links in the `<nav>` is now vertically aligned.
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/2188806/146411736-58ecc031-8459-4670-a970-a33730cd3e7d.png) | ![image](https://user-images.githubusercontent.com/2188806/146411771-0fd1bfe1-29e8-4e61-a46e-abad897571d1.png) |
Closes #983
> Vertically align nav links

- _data/sites.json
todoist.com settings url has changed from https://todoist.com/settings to https://todoist.com/app/settings/account
> Update url for todoist.com

- _data/sites.json
The site has been redone from scratch, and in this latest version a simple button has been added for deleting your account.
Update difficulty from 'impossible' to 'easy' for MangaDex
> Update MangaDex to easy

- _data/sites.json
- Added AirVPN
- Updated Raindrop.io's URL, difficulty, removed translation and added a domain.
- Updated showRSS's URL and difficulty.
- Updated Shutterfly's URL, difficulty, notes, removed translations and email.
- Shutterfly's [knowledgebase article](https://support.shutterfly.com/s/article/cancelling-deleting-customers-account) says they require a verification email into order to initiate the deletion process, however I did not need to do that to submit my deletion request.
I left out the notes for Raindrop.io and showRSS since the default note is fine there. The linked pages for both entries go directly to the account deletion page.
> Add AirVPN, update Raindrop, showRSS, Shutterfly

- _data/sites.json
- Added APKPure
- Added Freecycle
- Updated Honey's URL and notes.
- Updated Monster's URL, difficulty, and notes.
-  Unfortuately, Monster seems to have made it so you must contact them if you want your account deleted. The old URL shows a 404 error.
- Updated ImageShack's URL, added a note, and replaced a domain.
- Removed Voat
- Voat shut down on December 25, 2020
> Add APKPure, Freecycle, update Honey, Monster, ImageShack, remove Voat

- _data/sites.json
- Added iFixit (closes #1065)
- Added MyMaxon (closes #1066)
- Updated Swappa's url, difficulty, and notes. Removed email and email_body. (closes #1067)
- Removed Rovio
- Rovio's account service was discontinued on 3/18/2022. [Source](https://static.wikia.nocookie.net/angrybirds/images/5/57/RovioAccountClosure_Email.jpg)
> Add MyMaxon, iFixit, update Swappa, remove Rovio

- _data/sites.json
The duolingo entry linked to a page to disable your account, however, there is an option to permanently delete your account & personal data on duolingo. I linked this url instead, updated the difficulty since you have to go through an additional step, and added a new note accordingly.
> Update Duolingo entry to medium

- _data/sites.json
- Added TheTVDB
- Updated Monkeytype's name, url, difficulty, and notes.
- Updated OpenStreetMap's name, url, and difficulty. Removed notes and email.
- Updated Glassdoor's url, difficulty, and notes. Removed notes translation.
- While they say it can take up to 30 days for your request to be processed, mine was completed after around five minutes.
- Updated Kongregate (closes #1091)
- The link to your profile page (which the "Delete Account" button is located on) is username-dependent and can't be linked directly.
- Updated Microsoft Account to be `popular`.
- Removed Hotmail
- A Microsoft Account is used to log into Hotmail, so having this entry is redundant. Since this was a `popular` entry, I've added the `popular` meta tag to the Microsoft Account entry.
- Removed AppFog
- [AppFog v1 …
> Add TheTVDB, update Monkeytype, OpenStreetMap, Glassdoor, Microsoft Account, Kongregate, remove Hotmail, AppFog

- assets/js/scripts.js
Previously, hitting Enter while searching did nothing--you still had to wait the 250ms for the search to update. Now hitting Enter immediately updates the search term. Handy for those of us addicted to hitting enter while typing in input fields.
> Improve search responsiveness when hitting Enter

- _data/sites.json
Added an additional method for deleting a Humble Bundle account. The existing DSAR method is the easier and more recommended approach, however this additional method is an alternative in case the DSAR approach is not possible.
> Added Humble Bundle alternative

- _data/sites.json
- Added Hypixel Forums (closes #1094)
- Updated MediaFire's url and difficulty. Added notes and an email.
- MediaFire seems to have removed the option to delete your account yourself, and now requires an email to be sent.
> Add Hypixel Forums, update MediaFire

- _data/sites.json
Yes I know that "wordpress,com" is already there in sites.json but notice that "wordpress.org" is not.
https://wordpress.org/support/forum-user-guide/faq/#can-you-delete-my-account
> Add wordpress.org as impossible

- assets/css/style.css
The icon was previously being stretched to fit its flexbox parent. This PR changes its styling to center without stretching instead. The clickable area is not changed, so it is still very easy to click on as before.
| Before | After |
|:---:|:---:|
| ![Screenshot 2022-05-13 at 03-42-47 JustDeleteMe](https://user-images.githubusercontent.com/2199511/168207587-872d50c2-ae53-4ec1-ac9b-c9989cc0b967.png) | ![Screenshot 2022-05-13 at 03-42-54 JustDeleteMe](https://user-images.githubusercontent.com/2199511/168207589-b6ecf8c7-546d-4086-b453-54402a59856c.png) |
> Prevent stretching of language switch icon

- _data/trans/pt_br.json
The ISO 693-1 code pt_BR used in this website corresponds to Brazilian Portuguese specifically, not just Portuguese in general. And, indeed, by observing the language used throughout the website, the variant of Portuguese used corresponds to, indeed, Brazilian Portuguese.
Thus, it would make more sense to name the language in the menu accordingly, mostly for 2 reasons:
1. In loads of software, when the language states just "Portuguese", it is actually referring to European Portuguese (pt_PT), this should eliminate that redundancy.
2. It opens the door for the support of European Portuguese (pt_PT) in the website.
> Renamed "Portuguese" to "Brazilian Portuguese"

- _data/sites.json
- Added AV Club, The Onion, The Root, The Takeout, and The Inventory
- Dropped `(Gawker Media)` from existing kinja sites as the company effectively doesn't exist anymore.
- Removed Gawker, io9, and Valleywag (Gawker is not part of Kinja and has no account system, io9 is now part of gizmodo, and Valleywag is in an archived state - logging in is not possible anymore)
> Update Kinja sites

- _data/sites.json
[Club penguin ](https://techcrunch.com/2022/04/13/club-penguin-rewritten-shut-down-disney/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAACUD14MBejZeMwSHZTdphnYfhgcr4y5DExSWT37twE9R2jsjfrvFx7vmH9QWzyYKtwHede8ZkZQ-rHmnS9zfR0-ha1JZb-OL7DebupcsMA49crGVNqZ3KZYNWSSxV50_IJrNTO63PnwynCQk-0jBBwI2uQXPn28jOqoKNutneMYx) has been shut down. Removed entry, please feel free to reject this PR if this is not the correct process :)
> chore: removed club penguin rewritten

- _data/sites.json
Updated lingvist to easy as you can now delete your account from within the website and app. Turkish translation supplied by Google Translate
> chore: updated lingvist with new details for account deletion

- _data/sites.json
Stack Exchange accounts can now be marked for deletion with a single click even if posts have been made. It is not necessary to request support contact. Changed difficulty from "Hard" to "Easy" as per contributing guidelines and updated notes (english and spanish).
> Update details for Stack Overflow/Stack Exchange

- _data/sites.json
Add deletion steps for toyota.de
As this is a german page and there is no english translation, the description of the tabs/buttons is in german.
> Add toyota.de as easy

- _data/sites.json
Service closed on [May 17th, 2018](https://twitter.com/Storify/status/997204039807963137?cxt=HHwWgsC0lc7y49YbAAAA)
> Remove Storify

- _data/sites.json
Shut down by Reddit on [February, 2022](https://www.bloomberg.com/news/articles/2022-02-22/dubsmash-no-match-for-tiktok-dies-quietly-after-its-acquisition-by-reddit#:~:text=This%20week%2C%20according%20to%20announcement,the%20post%20about%20Dubsmash's%20demise.)
> Remove Dubsmash

- _data/sites.json
Site now redirects to whitehouse.gov
Old petitions can be seen at https://petitions.trumpwhitehouse.archives.gov or https://petitions.obamawhitehouse.archives.gov depending on when the petition was created, but the sites are now frozen and cannot be logged in to, as such I would be surprised if they still kept the user accounts since the petitions only show names.
> Remove We the People

- _data/sites.json
AWS retains account information indefinitely as far as I can tell. Their privacy policy says "a period of time" which they do not specify (all other signs point to it being forever).
> Change AWS to impossible

- _data/sites.json
This one took a while. The warner media privacy page (where the privacy policy sends you to) only accepts requests from california residents, and they verify your id. It only appears in the iOS app and is not linked anywhere at all.
> Add HBO Max as hard

- _data/sites.json
[Closed accounts are wiped after six months](https://support.wattpad.com/hc/en-us/articles/205292130-I-can-t-reactivate-restore-my-account)
> Change Wattpad to easy

- _data/sites.json
From what I can see, there is no option to sign in to the lenovo forums with a lenovo id anymore.
> Change Lenovo ID to hard

- _data/sites.json
A large cleanup of old sites:
- AllCall Forum: Site hasn't worked for years and does not indicate it will ever work again
- Beamly: Subdomain linked doesn't work, root domain redirects to coty, which does not have an account system
- ClickAndBuy: [The site was most likely shut down, as the company is no longer in business](https://web.archive.org/web/20220128235816/clickandbuy.com/faqs)
- Codenvy: Now uses the Red Hat account system
- Fast2Pay: Does not have any A/AAAA records at root or www, last successful wayback machine archive was in August 2021
- FogBugz: Now known as Glitch (which is already listed on jdm)
- Heroes of Newerth: [Game and site shut down on June 20, 2022](https://en.wikipedia.org/wiki/Heroes_of_Newerth#Development)
- Importa Brasil: Redirects to AliExpress
- Metacafe: …
> Remove old sites

- _data/sites.json
Previously the note told you to use the deactivate account process which doesn't fully delete your account. Recently the option to delete your account from the same page was added.
> Updated enjin note to actually delete account.

- _data/sites.json
UK food delivery service.
Marked as medium even though the deactivation process is very simple
because ensuring you are fully deleted (the terminology on the jdm
webpage) requires a GDPR request since the site is not transparent about
it.
> Add Deliveroo as medium

- _data/sites.json
Removing sites (Picasa and Google+) doesn't exist anymore.
> Remove Google+ and Picasa

- _data/sites.json
They point to a ticket form which says they will verify identity and residency.
> Add The Atlantic as limited

- _data/sites.json
They switched to a less atrocious link
> Update Best Buy Canada Link

- _data/sites.json
added `app.standardnotes.com` to `Standard Notes`
> Add subdomain for Standard Notes Web App

- _data/sites.json
removed `notes_pt_br` for investopedia, becuase it was identical to `notes`
Related to [#1394 ](https://github.com/jdm-contrib/jdm/pull/1394#issuecomment-1290285147).
> Remove notes_pt_br for investopedia

- _data/sites.json
They updated their privacy notice again, and it's less ambiguous than before. [Although there's more headaches for anyone that has a pre-2017 account and used the same email for their amazon.com account](https://confluence.cornell.edu/display/CLOUD/Interactions+of+AWS+Root+Accounts+and+Amazon.com+Accounts)
Now it's the same deal as everyone else ("we keep the stuff we need for tax purposes as long as we are required to keep it")
> Update AWS difficulty to medium

- _data/trans/de.json
The language used for the German translation was a bit stiff and uncommon.
> Remove honorific language in de.json

- _data/sites.json
I recently added Nexon as impossible because I couldn't open a ticket.
I contacted them by email and they sent me a link that allows sending a ticket for account deletion.
What happened is that their website is a bit complicated and everything isn't coherent. I asked them to fix that
So I'm marking Nexon as Hard and I set the link to the one the support sent me.
> Update Nexon from "Impossible" to "hard"

- _data/sites.json
The deletion link for IFTTT has been updated from https://ifttt.com/settings/deactivate to https://ifttt.com/settings/confirm_deletion
> Update IFTTT deletion link

- _data/sites.json
Asked DJI support to delete my account since I didn't want to download the app and got the following reply:
> DJI now supports the self-deletion of your DJI account, which only takes you 1-2 minutes and is also the quickest and easiest way to get it deleted. Please enter the link below---log into your DJI account to submit account deletion, our team will handle it as soon as possible.
https://account.dji.com/account/userCancel
> Update DJI to easy

- _data/sites.json
Quick question: I am a bit confused about marking this hard or limited, because the Washington Post claims in their account deletion confirmation email, that if you are a resident of EEA, UK, Switzerland, California, or Virginia, and you verified your address, they will delete additional information. It is not disclosed what this additional information is.
> Add The Washington Post as hard

- _data/sites.json
There's now a one-click way to delete your account. Tested with a dummy account.
However, according to the linked page, deleting your account does **not** cancel subscriptions, which requires additional steps.
> update The Guardian

- TRANSLATION_REFERENCE.md
- _data/trans/de.json
- _data/trans/kr.json
- _data/trans/nl.json
- _data/trans/tr.json
- _includes/body.html
This commit moves all post-extension-link text into translation files, preventing there from being a trailing space between the "Firefox Add-ons" link text and the period following it, incidentally preventing said period from wrapping to a new line on the English language page.
Fixes jdm-contrib/jdm#1583
> Remove space between extension text and period

- _includes/footer.html
As said in #1722 Robb Lewis now seems to have a different name and a different website. This pull request updates the footer accordingly.
closes #1722
> Update website for Robb Lewis

- _data/sites.json
Although their privacy policy states that data deletion can be requested by emailing privacy@spccard.ca, they have been unresponsive for months leading to the impossible classification.
> Add SPC as impossible

- _data/sites.json
This PR changed the removal "difficulty" from "hard" to "medium" as gnome.org allow easier account deletion.
| Scope | Screenshot |
|---|---|
| Account removal section |<img width="1440" alt="image" src="https://github.com/jdm-contrib/jdm/assets/48123439/a6a515ca-c123-4fa7-91d0-198664d9530d"> |
| Confirmation email | <img width="690" alt="image" src="https://github.com/jdm-contrib/jdm/assets/48123439/97ed8e45-d386-4500-9915-0c88f65044a3"> |
> Update Gnome to easy

- _data/sites.json
This closes #1801.
I added these domains in addition to the one suggested in the ticket:
* `reader.epoch.cloud`
* `epochtimes.bg`
* `epochtimes.com`
* `epochtimes.com.au`
* `epochtimes.com.br`
* `epochtimes.cz`
* `epochtimes.de`
* `epochtimes.fr`
* `epochtimes.it`
* `epochtimes.jp`
* `epochtimes.nl`
* `epochtimes.pl`
* `epochtimes.ru`
* `epochtimes.se`
* `epochtimes.sk`
* `epochtimes-romania.com`
* `epochtimestr.com`
* `epochtimesviet.com`
* `erabaru.net`
* `help.theepochtimes.com`
* `persianepochtimes.com`
* `theepochtimes.com`
* `es.theepochtimes.com`
* `kr.theepochtimes.com`
* `theepochtimes.gr`
> Add The Epoch Times as hard

- _data/sites.json
This closes #1794.
I added these additional domains to the one suggested in the ticket:
* `account.withings.com`
* `blog.withings.com`
* `healthmate.withings.com`
* `support.withings.com`
> Add Withings as easy

- _data/sites.json
This closes #1795.
I added these additional domains to the one suggested in the ticket:
* `blog.bikemap.net`
* `help.bikemap.net`
Also, since `url` is a required field I set it to `https://www.bikemap.net/`. Sadly we can't be any more specific, since the actual link for deleting the account includes `u/<username>`.
> Add Bikemap as easy

- CONTRIBUTING.md
- _data/trans/ar.json
- _data/trans/cat.json
- _data/trans/cz.json
- _data/trans/en.json
- _data/trans/es.json
- _data/trans/fa.json
- _data/trans/fr.json
- _data/trans/gr.json
- _data/trans/id.json
- _data/trans/nl.json
- _data/trans/pl.json
- _data/trans/pt_pt.json
- _data/trans/ro.json
- _data/trans/sk.json
- _data/trans/sr.json
- _data/trans/th.json
- _data/trans/vi.json
- _data/trans/zh-cn.json
- _data/trans/zh-tw.json
[Google Play has introduced their account deletion requirement](https://support.google.com/googleplay/android-developer/answer/13327111)
Given that you can run an android emulator and sideload the necessary apk on any computer that isn't a potato, it doesn't make sense to mark those entries as limited anymore.
> Remove app store language from limited guide

- script/validate_json.rb
The validate_json workflow now checks for duplicate entries. This closes #1810.
> Check for duplicate entries

- _data/sites.json
https://tapas.io/profile/settings
(easy) Scroll to the bottom, click "Delete Account", and click through the prompts.  You'll need to re-enter your password.
> Add Tapas as Easy

- _data/sites.json
Changed URL from one for data export to the one with the option to close one's account.
> Update Stripe's URL

- _data/sites.json
Added sections for Boostcamp and Shazam, hopefully I did it right this is my first time using Github and I just copy and pasted other easy entries and replaced the data.
> Add Boostcamp and Shazam as Easy

- _data/sites.json
Adds [Webhosting.dk](https://www.webhosting.dk/?nl=ENG).
**TL;DR** I've set the difficulty to **hard**, as you'd have to wait 5 full years in order to be allowed to go trough with the deletion.
In theory, the deletion is simple, as you just need to visit the provided link and login to delete one's account. However, according to the company, due to a legal requirement to retain information for the last 5 financial years, user accounts cannot be deleted even if they are no longer in use. This retention is necessary because the accounts are linked to domain names, payment details with Nets, and invoices, as mandated by law.
In other words, one must wait 5 fulls years. 
The company are, in fact, _allowed_ (although not _permitted_, as they claim) to retain this info.
I'm extremely annoyed, …
> Add webhosting.dk

- _data/sites.json
I asked the Department of State about it and their reply was:
```
Hello,  
Thank you for contacting us with regards to your STEP Enrollment.  
Unfortunately at this time, we are currently unable to provide profile deletion services. Profile deletion requires an enormous amount of data about yourself, and your trips, which places users at risk for potential fraud issues. Please be assured that your information will never be distributed and will only be used by the U.S. Department of State for Smart Traveler Enrollment Program’s purposes. Please also note that having an inactive account does not affect your enrollment status nor pose any security risk to you.   
We sincerely apologize for the inconvenience. Please let us know if you have any additional questions regarding STEP. 
Regards, …
```
> Add STEP as impossible

- _data/sites.json
Due to the absence of the "threads" site I decided to add it. Apparently, you cannot delete your thread account without first deleting your Instagram account, so I put the difficulty as "impossible" and the url is the same to delete your Instagram account.
> Added Threads to sites list

- _data/sites.json
The account deletion is now under the "Advanced" tab, and the URL reflects that.
> Update Zapier URL

- _data/sites.json
Chessable is a chess learning site that mainly includes courses from professional players.
https://www.chessable.com/about-us
> Add Chessable

- .github/workflows/workflow.yml
- .gitignore
- package-lock.json
- package.json
- script/check_files_formatting.sh
@htmlacademy/editorconfig-cli@2.0.0 and later appear to exhibit
different behavior, not actually triggering errors when editorconfig
discrepancies are found. This commit pins it to v1.0.0 and updates the
CI workflow accordingly.
Fixes #1966
To verify this on your system you can run `npm ci` followed by `./script/check_files_formatting.sh` on commit 8c61a5005bb2cd1c0f3122b685bbe0f2b425dc66 to see the non-0 exit code.
> Fix editorconfig CLI linting

- Gemfile
- Gemfile.lock
Not sure why we needed it and since when we stopped doing so, but it doesn't seem to affect anything.
> Remove unnecessary ffi dependency

- Gemfile
- Gemfile.lock
- _includes/header.html
- script/run_jekyll.sh
- htmlproofer `--checks-to-ignore` was [deprecated in v4](https://github.com/gjtorikian/html-proofer/blob/main/UPGRADING.md), we now have to set the checks we want and leave out the ones we don't
- The OpenGraph check caught that we had empty `og:url` and `twitter:url`. I hardcoded them because I didn't want to fiddle with `_config.yml`, maybe that's not the best approach
PS: I tried enabling the links check, but it fails on links with direct to text reference, like [this](https://www.outdooractive.com/en/k/how-do-i-delete-my-community-account-/50323147/#:~:text=Go%20to%20your%20page%20by,then%20select%20%22Delete%20Profile%22.)
> Update html-proofer to 5.0.8

- _data/sites.json
We at Scribd are going to remove the following link https://www.scribd.com/account_settings/preferences soon.
Thus, the PR does the following:
* Updates the [Scribd](https://www.scribd.com/) website information
* Updates the [Slideshare](https://www.slideshare.net) website information. The website is owned by Scribd
* Adds the [Everand](https://everand.com/) website information. The website is owned by Scribd
> Update Scribd-owned websites

- _data/sites.json
I've added the instructions for MathCad / PTC accounts.
Please be aware there is another section about a PTC product listing "ptc.com" under its domains.
I would appreciate some clarification how this duplication is handled.
If one or the other entry takes priority upon visiting ptc.com I suggest we combine "Vuforia Chalk" (the other product) and MathCad into a "PTC Accounts" section instead and combine their URL list, since PTC aquired Vuforia. The Vuforia section has spelling mistakes and an to my knowledge outdated support article anyways. In that case give me a ping and I'll fix it :)
That said, Vuforia developer accounts (developer.vuforia.com) are still separate from PTC accounts and would require their own section.
> Added Instructions for MathCad

- _data/sites.json
Added entries for Bluesky, iOSGods, Wizarding World, and Pottermore.
Wizarding World replaced Pottermore, but when attempting to login if the email address was previously associated with a Pottermore account it will say "Looks like you have a Pottermore account - Sign Up with Pottermore". Deleting the Wizarding World account and data does not delete any previous Pottermore data.
> Add Bluesky, iOSGods, Wizarding World, and Pottermore

- _data/sites.json
Update Booking (to hard), as at the moment the button to simply delete the account doesn't work (no confirmation email).
Notes languages: en & ru
> Update Booking to hard

- _data/sites.json
Added entry for [Inventory Shield](https://inventoryshield.com/support_docs/user-account-details/).
They don't have a direct link to the in-app account settings (yet), so this support article will have to do. I added notes that essentially mimic what the article says. Once logged in, the path to get to account deletion is very short.
Easy difficulty, since all users (with very few exceptions) are free to delete their account at will.
> Add Inventory Shield as easy

- _data/sites.json
Technically, pholder does not allow creating accounts, it just scrapes reddit and creates profiles automatically. Nevertheless, one might wish to delete their account from pholder.
> Add pholder as impossible

- _data/sites.json
threads.net now allows you to delete your Threads account only without it affecting your Instagram account.
> Update threads.net to easy

- _data/sites.json
I modified the difficulty and URL because it's easy to delete a You.com account. You just need to be logged in on You.com, go to your profile, and there's a delete account button.
> Update You to easy

- _data/sites.json
Hey there!
After reviewing their website, it is no longer necessary to contact their support, as it was before. At present, a button in the account settings provides the option to delete your account. Therefore, it simplifies the process.
I have also updated the URL and added a few translations.
A screenshot as evidence:
> Update Telltale to easy

- _data/sites.json
I have 3 accounts, all of which were last active in 2022 or earlier, but I can still log in to all of them successfully today. All of the data still seems to persist.
ref: https://www.reddit.com/r/Garena/comments/1apglbo/account_accessed_after_years_of_inactivity/?rdt=53062
my log:
> update note for garena

- _data/sites.json
Adds [Sourcegraph](https://sourcegraph.com) as hard to delete, as you'll need to contact their support by email.
> Add Sourcegraph with hard difficulty

- _data/sites.json
Walmart Canada's difficulty is now easy instead of hard because there is now a link in their footer to directly delete your account. Since this update involves a drastic change to the notes, it also removes the Turkish translation, as per the contributing guide.
> Update Walmart Canada to easy

- _data/sites.json
Added Marq as medium.
The value of the note key is a link to an article about how to delete your account, as the direct URL to account deletion is individual per user.
Simultaneously removed association between Lucidchart and Lucidpress, as Lucidpress was sold and later rebranded as Marq in 2022.
> Add marq as medium

- _data/sites.json
Yes, TCL has 4 separate accounts, for 4 branches of one service all linked to one physical card.
I don't understand either
> Add Fidélité TCL as easy

- _data/sites.json
Hello !
First of all thanks for this amazing website. It's so helpful.
The url for account deletion on Dashlane gave a 404 like page.
After a quick search in their forum I have the new url.
Here is the original [help article]( https://support.dashlane.com/hc/en-us/articles/202907531-Delete-your-Dashlane-account-and-data) from Dashlane.
I’ve modified the Dashlane url accordingly.
> Update Dashlane delete account URL

- _data/sites.json
Deleted Sharelatex as it was rebranded to Overleaf which is already registered.
Removed email-address from Overleaf as it is categorized as easy.
> Delete Sharelatex, Update Overleaf

- _data/sites.json
Added entry for Incogni as hard.
No official documentation seems to exist for account deletion except for https://support.incogni.com/hc/en-us/articles/18889349861266-I-no-longer-want-to-be-part-of-the-Incogni-Family-Friends-plan-can-I-delete-my-account.
> Add Incogni as hard

- _data/sites.json
They have too much URLs I cannot find them all.
As they have their own TLD is it possible to use just the TLD ?
> Add missing url to SNCF

- _data/sites.json
I added the vmware.com domain as everything that is done with VMware now has to do with Broadcom Support account
> Add Broadcom Support as Hard

- _data/sites.json
The site shutted down on July 31st, 2022 - https://help.elements.envato.com/hc/en-us/articles/360034211392-About-Twenty20
> Remove Twenty20

- _data/sites.json
According to the [gov.br's account terms of use](https://cadastro.acesso.gov.br/termo-de-uso) one can request deletion by contacting the help desk.
The previous link did not state it can't be done, just that there's no need (which is true as most online services require an account).
> Change gov.br's deletion instructions

- _data/sites.json
Zerotier: Easy
Tailscale: Limited (it's very hard to understand, the page linked is the best one I could find)
NetBird: Easy
> Add ZeroTier, Tailscale and Netbird

- _data/sites.json
(If the content in this PR doesn't make it clear, full disclosure: I am the owner of this website.)
The email address was originally included in the site's Just Delete Me listing before on-site account deletion was added. Although it's still possible to submit an account deletion request via email, no *valid* deletion requests have been made this way. I emphasize "valid" in the previous sentence because the only emails I've received claiming to be account deletion requests all follow the default `Please delete my account, my username is XXXXXX` email template associated with JDM, and there is no account data associated with the sender's email or that username. I would appreciate it if this teeny tiny burden was lifted from my shoulders :^)
> Remove email associated with galaxy

- _data/sites.json
STEP as it existed when it was first added is no more.
From the email I got, all accounts on the old STEP were wiped. New STEP relies on MyTravelGov, which itself uses login.gov as its account system (and we have an entry for that already).
I guess we could replace the entry instead but it makes little sense to do so.
> Remove STEP

- _data/sites.json
As a representative of **WayFi Wireless**, we are committed to respecting user privacy and ensuring that no data is retained against a user's wishes. We only store the information necessary for users to access and use our services.  
By submitting this request, we are adding **WayFi Wireless** to the account deletion list with the following details:  
- **Opt-out process:** Users can request account deletion by sending an email to **[privacy@wayfiwireless.com](mailto:privacy@wayfiwireless.com)** or filling out our [[contact form](https://wayfiwireless.com/contact)](https://wayfiwireless.com/contact).  
- **Deletion policy:** Requesting data deletion will result in the removal of all associated accounts.  
- **Automation status:** While our deletion process is **not automated**, we will …
> Add WayFi Wireless to Site List  

- _data/sites.json
As you can see also in the “How to delete your Apple Account” [page](https://support.apple.com/en-us/102559), they changed all the naming from Apple ID to Apple Account.
> Apple ID is now Apple Account

- _data/sites.json
I put all context in the first commit, but to reiterate:
* I updated from "easy" to "hard" because a support ticket must be filed
and an additional email sent to delete all data.
* I added an email for the separate data deletion step.
* I added notes to explain these changes.
Two things I'm unsure about:
1. Is using the email field for an additional step like this an okay usage of the field? Or should it be solely for account deletion?
2. I changed the URL to `.com`, but I want to make sure I'm supporting both `co.uk` and `.ca` for those respective regions. Would it make sense to add language support for both `en_gb` and `en_ca` for these cases respectively?
Lastly, I'm sending an email to the provided email to see if they'll both delete a test account and the data associated with it, so …
> Add NA, Spanish translation, email, and notes to Yelp; change difficulty to "hard"

- _data/sites.json
Specified as .com since there is also a .org. 
OpenSubtitles.com is the newer version but both still exist. They both use different accounts as far as I can tell.
See [here](https://opensubtitles.tawk.help/article/opensubtitlesorg-vs-opensubtitlescom) for the difference.
> Add OpenSubtitles.com

- _data/sites.json
I added a new entry for RemNote and translated the note field into Spanish. The note provides instructions for deleting your account, including the UI path (Settings > Profile > Account Deletion > Delete Account). I translated the note to Spanish but kept the UI path part in English due to RemNote's current lack of Spanish translation. Please let me know if it would be better to translate the entire field.
> Add RemNote as easy

- _data/sites.json
This pull request includes a change to the `_data/sites.json` file, where the difficulty level for the CZC site has been updated.
* [`_data/sites.json`](diffhunk://#diff-d90c9f1aae25e585903f8ef98912cba11bdb5e45ac27fbb2a096d1e98d2828a1L5361-R5361): Changed the difficulty level for the CZC site from "easy" to "medium".
> changed czc as medium

- _data/sites.json
The deletion process has changed. The earlier support website  content has also changed, though the website stays the same.
> Previously, account deletions could only be initiated by contacting us via email; however, we have now implemented an automated account deletion system that is more efficient and convenient for our customers to use. 
You can now delete your NordVPN account by deleting your Nord Account. This deletion will apply to all Nord Security products and services, including NordLocker and NordPass.
> Update NordVPN to easy

- _data/sites.json
The reason for 2 TrueNAS entries is that they set the old site to read only and the new site for the forums require a separate account.
> Added TrueNAS Forums, TrueNAS Forums (old), and fixed typo for Embark

- _data/sites.json
Ile de france Mobilités (Paris): medium
Note: not tested, linked the support page. Chose medium because the support page states that it's humanely processed and may take time
Rhonexpress (Lyon to Airport): easy
Ondéa Grand Lac (Aix-les-Bains): easy
Cars Région Savoie / Altibus (Savoie buses): hard (No deletion confirmation)
Sibra (Annecy): impossible (no response, considered impossible)
TAC Mobilités (Annemasse): easy
Synchro Mobilités (Chambéry): easy
Chamonix Mobilité (Chamonix): hard (after right request, waited 5min, so quick I missed it)
T2C Alertes (Clermont-Ferrand): hard (waited 2 weeks)
T2C Boutique (Clermont-Ferrand): easy
RLV e-boutique (Riom): easy
Mon espace STAS: easy
STAS Agence en ligne: hard (waited less than 24h)
Star't: easy
Valence Romans Mobilités: easy
L'VA: easy …
> Add almost all Auvergne Rhone Alpes transport services and Ile de France Mobilités

- _data/sites.json
- Updated deletion URL to `https://www.udemy.com/user/close-account/`
- Changed difficulty from `medium` to `easy`
- Replaced outdated notes with new instructions for closing an account
- Added fresh translations for all supported languages
- Expanded domains to include `www.udemy.com`
> Update Udemy entry with new deletion process and translations
