- sites.json
* All links on third party websites are broken.
* Help and docs point to no way of closing the account..
* Profile and management pages offer nothing related to closing an account.
> List napster as impossible

- sites.json
This was previous listed as impossible, while the notes clearly explained how do do it. It merely required deleting the associated Google Account (and that itself, is listed as easy).
I'm actually tempted to list this as easy, since there are no real "extra steps" here.
> Deleting a YouTube account is hard

- _trans/de.json
- sites.json
Also fixed a small translation error.
> Add Threema

- sites.json
> British Airways

- sites.json
as requested by https://github.com/justdeleteme/justdelete.me/pull/676
> Add arcor.de

- sites.json
Adds Quip to the list. They require that you contact customer support to delete your account, which is a bummer.
> Add Quip to sites.json

- sites.json
:dollar: :euro:
- Remove TweetDeck section as TweetDeck has been aquired by Twitter
- Rewrite YouTube and Speaker Deck sections as it's possible to delete those accounts now
> My 50 cents on the update of justdelete.me

- sites.json
Added account deletion information for Trillian to the sites.json file.
> Add Trillian

- gulpfile.js
- sites.json
This modifies the `jsonlint` gulp task to verify the sites are listed in alphanumeric order. The ordering disregards a beginning _the_. After implementing this task, I discovered several sites which were not in the correct order. Those changes are included here as well.
> Alpha check

- sites.json
Add an entry for DocuSign with a link to the customer support article for account deletion requests.
> Add DocuSign service

- sites.json
Rotten Tomatoes: Changes made to URL, difficulty and domain
> Updated Rotten Tomatoes

- sites.json
Re-submission of original PR at https://github.com/justdeleteme/justdelete.me/pull/636.
> Make Google URL more precise

- sites.json
Pastebin is easy to delete
See Issue #45
> Updated Pastebin (fix #45)

- sites.json
Added the Day One Journal Sync service
> Added Day One Journal

- README.md
Closes jdm-contrib/justdelete.me#70
Let me know if you'd prefer simpler or cleaner steps in any way; I tried to keep it slimmed down as much as possible without dumbing it down.
> Add build steps to README.md

- sites.json
Closed at [the original repo](https://github.com/justdeleteme/justdelete.me/pull/622) and reopened here. Good that this is still somewhat maintained!
> Added Deezer

- CONTRIBUTING.md
- README.md
Closes  jdm-contrib/justdelete.me#72
> Move Contributing section to own file

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Supersedes jdm-contrib/justdelete.me#34
This should also address the issues raised there with style / formatting guidelines.
> Christocoder update

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
According to jdm-contrib/justdelete.me#79, the site administrators may not follow up on account deletion requests. As such, its difficulty should be changed to "impossible".
Closes jdm-contrib/justdelete.me#79
> Update Asgardia.space in sites.json

- sites.json
> Add ProtonMail

- sites.json
1Password account will be deleted immediately.
> Add 1Password

- sites.json
Old description claimed emailing support was necessary. All that is required is logging in and using the delete account button.
> Updated Pandora

- sites.json
> Paper by FiftyThree

- sites.json
Account will be disabled (not deleted) immediately.
> Added Chess.com

- sites.json
Account data will be deleted. However, the user name will be blocked to prevent reuse. Hence, I chose "easy" severity. If you dissent, please amend.
> Added dict.cc

- sites.json
Account and its belonging data will be deleted immediately.
> Added YNAB

- sites.json
> Added Money Dashboard

- sites.json
Account will be deleted immediately.
> Added Simplenote

- sites.json
Add:
- Credit Karma
- Her Future
- Storenvy
Modify:
- Dwolla
- Remove trailing spaces
Contains changes originally submitted in https://github.com/justdeleteme/justdelete.me/pull/660.
> Add sites, delete trailing spaces

- sites.json
Changed URL which switches from the old to the new interface.
https://app.box.com/settings -> https://app.box.com/account
> Updated box.com

- sites.json
Add info for 3 sites: Collegeboard.org, FreeCodeCamp.org, and gPodder.net
> Add Collegeboard, FreeCodeCamp, and gPodder

- sites.json
The formerly described process isn't implemented yet. An e-mail has to be sent.
> Amended Raindrop.io

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- gulpfile.js
- package.json
- sites.json
- Adding new accounts
- Consistent naming and removing default `.com` from json files.
- Improving error handling by notifying user of sort order issues, easier to tell which site is out of order
- Building docs
- Adding gulp@^3.9.1 so it's consistent across developer env during builds.
> adding new accounts

- sites.json
Added 280daily, CodeProject, Dragdis, EATags, Fandom Wikia, GitLab, Magoosh, Pixlr, TrashMail, Weebly, Wikidot. Updated EA Origin.
EA Origin: http://answers.ea.com/t5/FIFA-15/want-delete-origin-account-How/td-p/3768843
Fandom Wikia: http://community.wikia.com/wiki/Help:Closing_an_account
GitLab: https://gitlab.com/help/user/profile/account/delete_account
Magoosh: https://magoosh.zendesk.com/hc/en-us/articles/204307485-How-do-I-delete-my-account-
> Added 11, Updated 1

- sites.json
> Added Player FM

- sites.json
> Add Proto.io & MarvelApp

- sites.json
Coursera now has a "Delete Account" button on the "Account Settings" page
> Updated Coursera

- sites.json
> Added Square Cash

- sites.json
> Adding Mockflow

- sites.json
> Add Discshop.fi

- sites.json
This is a Nordic e-commerce platform.
> Add CDON.COM

- sites.json
Recently discord added a button to delete your account. Changed it so it says to follow their guide.
> Updated discordapp.com

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Supersedes jdm-contrib/justdelete.me#136
To anyone reviewing/merging this PR, please use the "Rebase and merge" option to maintain the proper ownership of these commits; I didn't author them personally, so I want to make sure @diegotf30 gets correctly attributed for the work he did.
> Add CheapAssGamer, Leetcode, Mobills to site.json

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Ref: jdm-contrib/justdelete.me#153
> Add Conte.it to sites.json

- _trans/ru.json
small fix in russian translation
> Update translations in ru.json

- sites.json
transferring changes from old justdelete.me   
issue[#687](https://github.com/justdeleteme/justdelete.me/pull/687 "added netology study service - Update sites.json #687")
> netology study service in sites.json

- sites.json
Added CamelCamelCamel, Crowdin, Keepa and The Tracktor and made some cosmetic changes.
> Additions & Amendments

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Account will be deleted immediately.
> Added Cybrary

- docs/assets/js/scripts.js
Supersedes jdm-contrib/justdelete.me#173 [per PyroSamurai's comment](https://github.com/jdm-contrib/justdelete.me/pull/173#issuecomment-368718598)
> Remove Konami code easter egg

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
* Edited name
* Added notes
* Updated domains
> Updated Discordapp.

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Previous URL ended in a 404 when you clicked on "Close account"
> New URL for Coinbase

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Account will be deleted immediately
> Added Dock.io

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- gulpfile.js
- package.json
- sites.json
Also updates all notes where links were present already to use `<a>` tags.
Closes jdm-contrib/justdelete.me#27
> Allow <a> within notes

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Deletion info as provided by https://webcache.googleusercontent.com/search?q=cache:_vIrn_TF9mYJ:https://publiclab.org/notes/alanrday/03-05-2018/how-do-i-delete-my-publiclab-account+&cd=1&hl=en&ct=clnk&gl=br
> Add Public Lab

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
This also removes redundant "domain" entries and fixes some entries
based on updates from investigating contact email addresses.
> Add missing email property entries

- sites.json
> Remove extraeneous domains

- sites.json
> Add Premiumize.me

- CONTRIBUTING.md
- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- gulpfile.js
- sites.json
- template.html
Closes jdm-contrib/justdelete.me#180
> Add support for email_body and email_subject fields

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
This is a PR to fix PR #112. At some point I deleted the repository that I used for the original PR, so GitHub won't allow me to re-open that PR. I am not altogether sure why I closed the original one, sorry for the confusion.
This PR also fixes the difficulty (now `"impossible"`).
> Add Unity ID (again)

- docs/ar.html
- docs/cat.html
- docs/de.html
- docs/es.html
- docs/fa.html
- docs/fr.html
- docs/id.html
- docs/index.html
- docs/it.html
- docs/nl.html
- docs/pl.html
- docs/pt_br.html
- docs/ro.html
- docs/ru.html
- docs/sk.html
- docs/sr.html
- docs/th.html
- docs/tr.html
- docs/vi.html
- docs/zh-cn.html
- docs/zh-tw.html
- sites.json
Old URL one.ubuntu.com is orphaned
> Changing URL of Ubuntu One in sites

- _data/sites.json
Unfortunately, the URL is different for every region
> Add Habbo to sites

- _data/sites.json
Due to GDPR Steam has added the ability to delete your account. I have updated the notes which means I unfortunately had to delete the previous translations.
> Updated Steam

- _data/sites.json
Disqus link was out of date. Updated it.
> Updated Disqus URL in  sites.json

- _data/sites.json
Changed the difficulty of some sites to easy or hard from medium as they would be better classified under them. Also updated a few outdated urls. (#231)
> Change some medium services to easy or hard and update some urls

- _data/sites.json
> Update GMX.net difficulty

- _data/sites.json
> Update wordpress difficulty

- _data/sites.json
Update to match the info provided in issue #223
> Update Airbnb info

- _data/sites.json
Closes #238 
Might have to be updated depending on #238 followup
> Add Humble Bundle

- _data/sites.json
It doesn't exist anymore. Closes #241
> Remove Boxee.tv

- _data/sites.json
It doesn't exist anymore. Closes #242
> Remove Desktop.ly

- _data/sites.json
It doesn't exist anymore. Closes #240
> Remove Affero

- _data/sites.json
> Update Humble Bundle difficulty to 'Impossible'

- _data/sites.json
Removed Spring.me and Yatado because they are no longer working
> Added The Artist Union and removed Spring.me and Yatado

- _data/sites.json
https://www.overleaf.com/help/299-how-do-i-delete-my-overleaf-account
> Add Overleaf

- _data/sites.json
+ AbeBooks
+ BookBub
+ Cacoo
+ CryptPad
+ Delivery Code
+ Dreamwidth
+ Freeletics
+ PlayPosit
+ Yummly
> Add several sites

- _data/sites.json
DansTonChat is a popular french quote database, similar to bash.org
> Added DansTonChat to sites.json

- _data/sites.json
I put the difficulty as hard because XDA makes you fill a form which they use to manually process the form, you also have to specify if you want your posts deleted rather than just anonymised.
> Added XDA Developers

- Gemfile
- Gemfile.lock
This commit resolves several open vulnerabilities of some of our dependencies.
> Update Gemfile dependency versions

- _data/sites.json
> Remove websites that have gone offline - Closes #260

- _data/sites.json
> Add keybase.io - Closes #259

- _data/sites.json
> Update sites.json - Added Yandex

- _data/sites.json
> Add Babbel to sites.json

- _data/sites.json
> Add munzee netlify

- _data/sites.json
The service has been shut down
> Remove Tunngle

- _data/sites.json
> Update Change.org URL

- _data/sites.json
> Add Heroes of Newerth

- _data/sites.json
> Add Garena

- _data/sites.json
**Survey Monkey** made it easy to delete the account and I modified the **sites.json** file in the corresponding field.
> Update SurveyMonkey entry

- _data/sites.json
> Add ProductHunt

- _data/sites.json
> Update 500px difficulty

- _data/sites.json
> Add Faceit

- _data/sites.json
I contacted support and they told me it's due to technical limitations not possible to delete an account.
> Added Social Blade

- _data/sites.json
wishsimply (wishsimply.com) is a public wishlist service. alternative for an amazon wishlist.
> updated sites.json by adding wishsimply to it

- _data/sites.json
Please enter the commit message for your changes. Lines starting with \'#' will be ignored, and an empty message aborts the commit.
> Spotify ain't easy!

- _data/sites.json
This pull request adds entries for the following services:
- Codeanywhere
- Native Instruments
> Add 2 new sites.

- README.md
This is my very first time forking from an open source project, so I wanted to start off small.
Simply changed `bundler install` to the correct command `bundle install`.
> Update install command for bundler to be more accurate

- _data/sites.json
<h3 align='center'>Changes</h3>
* **Updated:** `difficulty`, `notes` and `notes_pt_br` of the "Mercado Libre Uruguay" account deletion info
* **Added:** "Mercado Libre Argentina" account deletion info
* **Added:** "Mercado Libre Bolivia" account deletion info
* **Added:** "Mercado Libre Chile" account deletion info
* **Added:** "Mercado Libre Colombia" account deletion info
* **Added:** "Mercado Libre Costa Rica" account deletion info
* **Added:** "Mercado Libre Ecuador" account deletion info
* **Added:** "Mercado Libre Guatemala" account deletion info
* **Added:** "Mercado Libre Honduras" account deletion info
* **Added:** "Mercado Libre México" account deletion info
* **Added:** "Mercado Libre Nicaragua" account deletion info
* **Added:** "Mercado Libre Panamá" account deletion info
* …
> Add more websites

- _data/sites.json
<h3 align='center'>Changes</h3>
* **Updated:** `name`, `url`, `difficulty`, `notes` and `notes_pt_br` of the "Njalla" account deletion info
* **Added:** "Muambator" account deletion info
* **Added:** "textPlus" account deletion info
* **Added:** "Freenom" account deletion info
<h3 align='center'>Additional information</h3>
The domain `nextplus.me` are related to same type of account, so I have also included it in the "textPlus" account deletion info.
Closes: [#349](http://github.com/jdm-contrib/jdm/issues/349).
> Add new websites to sites.json

- _data/sites.json
The free account can be deleted instantly, however, the paid version requires you to first cancel the subscription. That's why I decided to go for "medium".
Additional resources:
https://help.jimdo.com/hc/en-us/articles/115005540586-How-do-I-delete-my-Jimdo-account-
> Added Jimdo

- _data/sites.json
These were pointed out by [Build #931](https://travis-ci.org/jdm-contrib/jdm/builds/592863759).
From the commit messages:
> Website stopped responding.
> Social media account seems to be inactive:
> https://twitter.com/cheddarapp
> Failed to respond to request
> Social media account inactive for > 5y
> https://twitter.com/icebergsapp
MyFritz is also timing out, but it has an active social media account and was added a month ago, so I'm considering it might be a temporary issue.
> Remove stale

- _data/sites.json
> Update Spotify to Medium

- _data/sites.json
Added [Authy](https://authy.com) app.
The form is [here](https://authy.com/account/delete/).
They ask you to check if you've disabled 2FA on all accounts you've added to the app.  
Then, they ask you to enter your phone number and type a code from SMS.  
After that, they'll show you a list of sites and again ask you to check if you've disabled 2FA.  
Finally, they'll send you an e-mail with links to continue or cancel the process. Cancellation link will be active for the next 30 days.
> Add app authy.com

- _data/sites.json
> Add Lime (li.me)

- _data/sites.json
- _includes/header.html
<h3 align='center'>Changes</h3>
* **Updated:** Sharing link of the "Tweet JDM" button/widget
* **Added:** "Dailymotion" account deletion info
* **Added:** "Dubsmash" account deletion info
* **Added:** "Samsung Account" account deletion info
* **Added:** "Supercell ID" account deletion info
<h3 align='center'>Additional information</h3>
<h4 align='center'>Supercell ID</h4>
Supercell ID is an account used to save and sync the progress of Supercell's mobile games (it's something like Google Play Games).
Even after "delete" the account, Supercell will still keep users' personal information saved on its servers to, according to them, "business interests".
* [How do I delete my account? | Bom Beach](http://supercell.helpshift.com/a/bom-beach/?s=my-account&f=how-do-i-delete-my-account)  
* [How …
> Account deletion at Supercell ID, Dailymotion, Dubsmash and Samsung

- _data/sites.json
They answered me about a week later and deleted, so I'm changing to hard.
> Update CodersRank difficulty

- _data/sites.json
This pull request adds entries for the following services:
- VSTBuzz
- RapidAPI
- Sketchfab
> Add 3 new sites.

- _data/sites.json
Closes #380 
I found out that it is deletable by contacting them via e-mail and the entry actually said that, so I just changed the URL and the difficulty to describe more faithfully
> Update Giant Bomb

- _data/sites.json
It was erroring out on the latest builds of Travis. This seems to be the new link
> Update Scaleway Website

- _data/sites.json
> Add Nextdoor

- _data/sites.json
Following @Nightfirecat suggestion for PR https://github.com/jdm-contrib/jdm/pull/386, I tried to create a new branch on my repo and PR from it.  
It seems to work now, I will know it for my next PR :)
> Add Fasttech

- _data/sites.json
<h3 align='center'>Changes</h3>
* **Updated:** `notes`, `notes_pt_br`, `notes_pl` and `url` of the "DigitalOcean" account deletion info
* **Updated:** `url` of the "Supercell ID" account deletion info (typo)
* **Updated:** `notes_pt_br` of the "Samsung Account" account deletion info (typo)
* **Added:** "Crypton.sh" account deletion info
* **Added:** "Tutanota" account deletion info
* **Added:** "EBANX" account deletion info
* **Added:** "Celcoin" account deletion info
* **Added:** "Lolja" account deletion info
* **Added:** "RecargaPay" account deletion info
* **Added:** "Android File Host (AFH)" account deletion info
* **Added:** "PicPay" account deletion info
> Account deletion at Tutanota, EBANX, Crypton.sh and many others

- _data/sites.json
Added information for [nordpass.com](https://nordpass.com).
Customer support will ask you to tell why are you deleting an account and after that will ask you for a deletion confirmation. CS responses are pretty slow (the whole process took ~6 days for me).
> Add nordpass.com

- _data/sites.json
Heh, delete your friend's account.
> Napster you can delete your account.

- _data/sites.json
> Update Slashdot difficulty

- _data/sites.json
> Update League of Legends link

- _data/sites.json
Copied this PR from the defunct repo: https://github.com/justdeleteme/justdelete.me/pull/779
> Add forvo.com

- _data/sites.json
This adds the changes from #421, which I accidentally closed with an errant force-push. (sorry @BilelJegham!)
> Add Headliner

- _data/sites.json
I added some websites to this updated fork after being asked if it was possible to bring the changes here, on this pull request: https://github.com/justdeleteme/justdelete.me/pull/803
Thank you for your attention.
> Added various websites

- _data/sites.json
> Update Autodesk to easy

- _data/sites.json
> Add AliExpress

- _data/sites.json
> Add SoftCreatR Media

- _data/sites.json
> Added saschamoser.de

- _data/sites.json
> Add TKirch.dev

- _data/sites.json
> Add statcounter

- _data/sites.json
Changes based on Issue #439 
Changes to be committed:
modified:   _data/sites.json
> Updated info on Photobucket due to their website redesign

- _data/sites.json
> Add ViaBox

- _data/sites.json
> Update sites.json - Added bet365

- _data/sites.json
> Update GoDaddy difficulty to easy

- _data/sites.json
You can't actually delete your reddit account but rather just deactivate it (unless you happen to live in the EU).
I also changed the difficulty to hard considering the fact that (if you are an EU citizen) you have to inquire via e-mail if you actually want your account deleted.
>  Update reddit entry

- _data/sites.json
> Add Rosetta Stone to sites.json

- _data/sites.json
> Add MeetFrank

- _data/sites.json
Good day! Here's an image by [Tadeusz Lakota](https://unsplash.com/@tadekl).
> Add Nvidia

- _data/sites.json
Co-Authored-By: Gracjan <gracjankn@users.noreply.github.com>
> Add description to GitHub

- CONTRIBUTING.md
- _includes/body.html
- script/validate_json.rb
Closes #458 
Let me know what you think
> Allow localized url

- _data/sites.json
> Add OpenDesktop

- .github/ISSUE_TEMPLATE/new_entry.md
- .github/ISSUE_TEMPLATE/update_entry.md
This is how the template looks like for each:
> # Backstory
> 
> 
> # Data
> 
> 
> - `name`: 
> - `url`: 
> - `url_CODE`: 
> - `difficulty`: 
> 
> - `notes`: 
> - `email`: 
> - `email_subject`: 
> - `email_body`: 
> - `domains`: 
> # Backstory
> 
> 
> # Data
> 
> 
> - [ ] `name`: 
> - [ ] `url`: 
> - [ ] `difficulty`: 
> - [ ] `notes`: 
> - [ ] `email`: 
> - [ ] `domains`:
> Add templates for new or updated entry issues

- _data/sites.json
> Fix wrong site name

- _data/sites.json
Maxdome is a German video streaming site.
> Added Maxdome

- _data/sites.json
Definitely not easy. If you're a member of a workspace you can only "deactivate" yourself. You must ask workspace admin or Slack support for a full deletion and your history is still there.
Maybe should be hard?
> Update slack to medium

- _data/sites.json
Expedia is a travel site. It has multiple domains, all of which can be used with the same account. More domains need to be added when necessary.
By the way, is adding of new sites intended via PRs or via the new issue template? Thanks for your work on this!
> Added Expedia

- _data/sites.json
Wedbio.com is a wedding website that specializes in Elegant Wedding Website Design, Invitations, Online RSVP, Guests List, Event Reminder, Reporting, e-Wallet, and more.
Thank you for your work!
> Added wedbio

- _data/trans/ar.json
- _data/trans/cat.json
- _data/trans/de.json
- _data/trans/en.json
- _data/trans/es.json
- _data/trans/fa.json
- _data/trans/fr.json
- _data/trans/gr.json
- _data/trans/id.json
- _data/trans/it.json
- _data/trans/nl.json
- _data/trans/pl.json
- _data/trans/pt_br.json
- _data/trans/ro.json
- _data/trans/ru.json
- _data/trans/sk.json
- _data/trans/sr.json
- _data/trans/th.json
- _data/trans/tr.json
- _data/trans/vi.json
- _data/trans/zh-cn.json
- _data/trans/zh-tw.json
I don't think they have ever added that much value, and removing them makes the translation job a lot easier for non-developers
> Remove &nbsp; from translations

- _data/sites.json
I've finally set up proxy and finished work started in #490 :smile_cat:
> HTTPS for LinkedIn and DailyMotion

- _data/sites.json
Changed difficulty to medium, because you have to
> Enter your password, then enter a 6-digit code that will be sent to your email and click 'Delete Account'. You can recover the account within 30 days of deleting it. The deletion is completed in 90 days
Source: https://knowledge.autodesk.com/customer-service/account-management/account-profile/account-security/delete-your-autodesk-account and tried it myself
> Updated Autodesk to medium

- _data/sites.json
You can close https://github.com/jdm-contrib/jdm/pull/504
This one has the fixed formatting.
> add Ferox Hosting

- _data/sites.json
After easyjet hack more people will be looking to remove personal details from other airlines.
Hope this helps.
> Add new site (ryanair.com) to sites.json

- _data/sites.json
As suggested by @xhamyd . I took the text that states it was only tested for the trial account.
Closes #512
> Add Bluejeans

- _data/sites.json
Suggested by @jtagcat, please review and comment
Closes #509
> Add Melodics

- _data/sites.json
They replied quite quikly.
Closes #517
> Add Mendeley

- _data/sites.json
Looks like `note` without the `s` makes the note not show up.
> Fix typo, otherwise attached note doesn't show up in website

- _data/sites.json
- script/validate_json.rb
Closes #523 
Funny enough it already paid off as each of the methods found an error in our JSON 🚀
> Make sure linting disallow unsupported json keys

- LICENSE
- README.md
> Edit License info

- TRANSLATION_REFERENCE.md
- _data/trans/ar.json
- _data/trans/cat.json
- _data/trans/de.json
- _data/trans/en.json
- _data/trans/es.json
- _data/trans/fa.json
- _data/trans/fr.json
- _data/trans/gr.json
- _data/trans/id.json
- _data/trans/it.json
- _data/trans/kr.json
- _data/trans/nl.json
- _data/trans/pl.json
- _data/trans/pt_br.json
- _data/trans/ro.json
- _data/trans/ru.json
- _data/trans/sk.json
- _data/trans/sr.json
- _data/trans/th.json
- _data/trans/tr.json
- _data/trans/vi.json
- _data/trans/zh-cn.json
- _data/trans/zh-tw.json
- _includes/body.html
- _includes/footer.html
- _includes/header.html
- script/validate_json.rb
> Wording: Encourage contributing and PRs instead of forking the project on GitHub.

- _data/sites.json
> Added EasyEDA entry

- _data/sites.json
> plexguide.com

- _data/sites.json
Included a link along with instructions to delete a peopleperhour.com account.
> Added site deletion info to sites.json

- _data/sites.json
> GameGleam.com

- _data/trans/vi.json
```
"contribute": "Contribute on GitHub"
"pullrequest": "Make a Pull Request on GitHub"
```
> Update outdated terms

- _data/sites.json
Source for last sentence in notes:
https://help.cengage.com/mindtap/mt-student/common/delete-acct.html
> Add Cengage

- _data/sites.json
> Add Carbonmade

- _data/sites.json
> Add Mathway

- _data/sites.json
This was sent to me on another social media, they all seem impossible
> Add some feed readers

- _data/sites.json
Deleting account is very easy now.
> update freelancer info

- _data/sites.json
> Edited Unity ID difficulty

- _data/sites.json
Remove link to broken support page
> Update CEX.io link

- _data/sites.json
Figure these make sense as a single entry since they are interlinked and deletion information is all provided on a single page. Name written out fully for searchability.
> Add Technic Platform & Forums

- _data/sites.json
> Add Bitfinex

- _data/sites.json
> Update Fitbit to easy

- _data/sites.json
Support doc: https://help.remind.com/hc/en-us/articles/200917769-Delete-your-account
> Add Remind.com

- _data/sites.json
Glovo seems to require filling up a free text to be reviewed.
> make glovo hard

- _data/sites.json
Despite the wording of the link, the website does state that personal data is removed:
https://prnt.sc/uzkjpt
> Add Stock Informer

- _data/sites.json
Per https://support.runescape.com/hc/en-gb/articles/360001370829-Your-personal-data-rights, previous instructions are out of date
> Update Runescape with current deletion process.

- _data/sites.json
> Add GitKraken

- _data/sites.json
> Add Kaspersky

- _data/sites.json
As in the title.
This process can be verified by viewing the settings page while logged in and reading the information presented.
> Add instructions for Internet Archive

- _data/sites.json
I remove my domain since I deleted the website and letting the domain end. So nothing is hosted anymore for this.
> Removal of xopsblog.de

- _data/sites.json
I couldn't figure out where to go with the current notes. The location and labels might have changed in the last months.
https://support.zoom.us/hc/en-us/articles/201363243-Deleting-or-terminating-your-account helped me find it.
My changes hopefully clarify how to get there without having to consult the Zoom Help Center.
> Update Zoom note

- _data/sites.json
Klarna is an installment payments company as far as I can tell. To delete your account you have to contact customer service.
Their description of how to do this is here: https://www.klarna.com/us/customer-service/how-do-i-close-my-klarna-account/
> add Klarna to sites.json

- _data/sites.json
Add [Too Good To Go](https://toogoodtogo.com/).
As you have to do more than just clicking on a button, the difficulty could also be medium.
Thanks @tupaschoal for directing me here.
> Add Too Good To Go

- _data/sites.json
Added the instructions on how to delete an account on [Textures.com](https://www.textures.com/).
> Add Textures.com

- _data/sites.json
Added Bohemia Interactive and Rockstar Games Social Club.
> Added two new sites

- _data/sites.json
The official way to delete accounts used with the MyPlate app.
> Add entry for MyPlate

- _data/sites.json
Honey's pretty easy, but good to have it nonetheless
> Add Honey to list of sites

- _data/sites.json
> Add Ada to list of sites

- _data/sites.json
instructions are buried at the end of their faq page
> Add twoseven to list of services

- _data/sites.json
Also removed linked turkish notes, as they'd be outdated.
> Cloudflare now has a delete-your-account form.

- _data/sites.json
I think its `hard` because you have to submit a request, though i'll change if its else
> Add funimation.com

- _data/sites.json
edX did not allow deletion of account but it does now. 
Also I have marked that as medium since you may have to unlink your accounts manually since they don't allow deletion before that.
https://support.edx.org/hc/en-us/articles/206915007-How-can-I-delete-my-account-
All other are VPN services 👍
> Added NordVPN, Surfshark, ProtonVPN. Edited edX.

- _data/sites.json
> Add O'Reilly

- _data/sites.json
Instructions do not match anymore
> Remove Arcor.de

- _data/sites.json
Site has gone completely offline and has no record on the wayback machine
> Remove Dock.io

- _data/sites.json
Papara is mainly a Turkish service so please feel free to not include it if you feel like it doesn't suit the project. Also, I was planning to do one more Turkish service that starts with "Ç". Where would that be in the alpabetical listing, if it is even allowed? Thank you.
> Added Codeberg and Papara

- _data/sites.json
These should be the most common shopping sites in my country. As ÇiçekSepeti starts with extended ASCII, I put it at the most bottom.
> Added Gittigidiyor, Hepsiburada, Letgo, N11, Sahibinden and ÇiçekSepeti

- _data/sites.json
You can only call/request a call from EA if you are within the US or Canada and I was able to delete my account by just contacting support with live chat.
> Updated EA and added Paradoxplaza and Vivaldi

- _data/sites.json
It actually might not be easy, as I found out the button just opens a ticket to their support. Will hold this until I get an answer
> Add Rail Europe

- _data/sites.json
- Add Ludum Dare
- Add ProMods
> Add multiple sites

- _data/sites.json
> Add blinkee.city

- _data/sites.json
Didn't found on your database so I added it.
> Added Sonos.com

- _data/sites.json
This deletion process is a bit of a runaround, but their policies and confirmation emails indicate a reasonable erasure of personal identifying data.
> Add ScholarshipPoints

- _data/sites.json
This one was pretty quick. I sent the request email over the weekend, and the day that they opened I received confirmation of account deletion.
> Add Ten Percent Happier

- _data/sites.json
> Update apple notes

- _data/sites.json
**Atlassian Update**
**Updated**:
- Difficulty Easy >> Medium
- Notes
- Secondary URL
**Notes:**
If the account has an existing subscription active or cancelled you are required to designate another user as the primary billing and  and technical contact. Atlassian will **not** let you delete your account otherwise.
> Atlassian Update.

- _data/sites.json
Removing your account with **Hover.com** is as easy as canceling your service. 
Hover only mentions this in their help article provided below.
https://help.hover.com/hc/en-us/articles/222421328-Canceling-services-with-Hover
> Add Hover.com

- _data/sites.json
Solves #836 thanks to @ghost for the translations for most of the websites that start with 'A'.
**Notes:**
Might as well not let it go to waste. Please comment any suggestions or point out any errors in the translation before merging it to master.
French is my 2nd language so I'll probably end up translating all of it in french at one point; that'll be in another PR.
**This better not disappear like the last PR** 😡
> Translated notes on 'A' to russian. 

- _data/sites.json
Leaving this PR as a draft in case I can get to a support rep.
EDIT 1: Finally got hold of a support rep. They said they would inquire with Hooked's tech team about deleting my account. They also told me that forgetting my login credentials may be the best recourse.
~~I'll leave this in draft for a while, in case I hear back with other news.~~
EDIT 2: Deletion is a no-go.
> Add Hooked Deals

- _data/sites.json
Can't remove an account, but can remove personal information.
> Add Intelius

- _data/sites.json
Added support for [AirMeet](https://www.airmeet.com) with instructions in English and Portuguese.
> Added support for AirMeet

- _data/sites.json
I saw that I had used the wrong url for ultimate guitar.
> Fixed Ultimate guitar URL

- _data/sites.json
I think it's at the right place after ripe...
> added rituals.com

- _data/sites.json
Does this change look right @u0nel?
> Close #918: Update Scaleway instructions

- _data/sites.json
https://support.unity.com/hc/en-us/articles/360000878446-How-do-I-permanently-delete-my-Unity-account
> Update Unity ID to easy

- _data/sites.json
Add [Bukkit](https://bukkit.org/).
> Add Bukkit

- _data/sites.json
I added swappa.com. It is categorized as 'hard' because you have to email customer service. I emailed them and they promptly deleted my account via email: help@swappa.com.
> Added Swappa.com

- _data/sites.json
Added Drizly.com as 'hard'. Their website requires a user to email them and fill out an online form.
> Added Drizly.com

- _data/sites.json
Once again you have to email customer service so this one too is listed as 'hard'. I gave the contact page link where you use a web form to email customer service.
> Added Vans.com

- _data/sites.json
Added [OVHcloud UK](https://www.ovh.co.uk).
> Added OVHcloud UK.

- _data/sites.json
> Add Challonge.com

- .github/ISSUE_TEMPLATE/new_entry.md
- .github/ISSUE_TEMPLATE/update_entry.md
- CONTRIBUTING.md
- README.md
As per #943, separate PR to bring docs into markdown lint compliance
> Markdown Lint compliance

- _data/sites.json
> Add ITV.com

- _data/sites.json
Added [brut.media](https://www.brut.media) and [uxcel.com](https://uxcel.com)
> Added Brut.media and uxcel.com

- _data/sites.json
Hello, this is my first contribution here. I hope I've formatted this properly. The JSON passes the jsonlint.com validation test.
> Add shopyourway.com

- _data/sites.json
I recently wanted to delete my utry.me account and found out the only way to do this is to request the deletion by email.
If I had this information beforehand, I wouldn't have created an account there.
Just contributing to make people have the information handy, that would've helped me earlier.
> Add utry.me

- _data/sites.json
@unknown4849 I translated the notes to English using Google Translate, as `notes` are used for English notes.  Do they look right?
> Close #974: Update Tokopedia to hard

- _data/sites.json
Added another service with hard to delete account.
> Add Bkool.com as hard

- _data/sites.json
> Fix Fiverr markup

- _data/sites.json
Changed the difficulty, URL and notes
> Update browserstack.com in sites.json

- _data/sites.json
Just two basic additions to the list.
> Add nandos.co.uk, tryhackme.com

- _data/sites.json
* Add AKAI Professional
* Add BeamNG
* Add FMOD
* Add FontStruct
* Add forward2me
* Add Guilded
* Add Linode
* Add MyFonts
* Add Opera
* Add Parsec
* Add Read the Docs
* Add Replit
* Add Revolt
* Add SpaceHey
* Add speedrun.com
* Cannot directly link as the deletion page needs your username in the URL
> Add 15 sites

- _data/sites.json
> Add expo.dev

- _data/sites.json
- Added Teespring (closes #992)
- No response to emails about account deletion.
- Added 8tracks
- 8tracks has provided an option to delete your account, but it doesn't work. I've sent an email on November 25 letting them know, but haven't gotten a response, so I'm adding as impossible for now. Judging by their FAQ, [it appears they have other issues to deal with right now.](https://8tracks.com/faq#question-51)
> Added Teespring, 8tracks

- _data/sites.json
I recently deleted this account and it led me to a 404, but going to the new url worked
> Fixed Lookout.com Link

- _data/sites.json
I noticed this site was not here, so I decided to add it
> Add smule.com and TickTick

- _data/sites.json
Add instructions for account deletion on [Reservio](https://www.reservio.com/).
> Add Reservio

- _data/sites.json
My wife and I just went through the steps to delete our HelloFresh account. 
Documenting it here.
> Add an entry for HelloFresh

- _data/sites.json
> Add Mibbit

- _data/sites.json
> Add XSplit

- _data/sites.json
According to the website's privacy policy (https://boardgamesonline.net/Help/privacypolicy#rightToErasure) they have added a button to request account deletion, which they will do in about one week.
I tested it with my own account that I wanted to delete, they did in fact delete it in a week.
> Update Board Games Online to easy

- _data/sites.json
Didn't see this website on the database, so i figured I should contribute! Seems pretty easy to do it :) Tested with CI/CD so i can make sure I formatted it properly!
> Add resumegenius to the website

- _data/sites.json
I added the Love My Credit Union Rewards service to line 6332.
> Add Love My Credit Union Rewards

- _data/sites.json
> Update HackThisSite to easy

- _data/sites.json
Added Mouser
https://www.mouser.co.uk/privacypolicy
> Add instructions for Mouser

- _data/sites.json
> Add Auth0 as hard

- _data/sites.json
- [16Personalities](https://www.16personalities.com/)
- [Anti-Captcha](https://anti-captcha.com/)
> Add 16Personalities and Anti-Captcha

- _data/sites.json
- Added Rev (closes #1059)
- Added OneCompiler
- I couldn't link directly to the account settings page since the URL must contain the logged in user's account ID number.
- Updated ByDoor notes
- Changed duplicate `notes` key to `notes_pt_br`
> Add Rev, OneCompiler, update ByDoor

- _data/sites.json
Added [dbrand](https://dbrand.com/), a brand of expensive stickers for electronic devices.
> Add dbrand as hard

- _data/sites.json
No response to deletion request email after 5 weeks.
> Add DoIT.life as Impossible

- _data/sites.json
We've changed the way we do this since this was added in 2014, but hopefully it should still be perfectly easy. I don't speak Turkish though, so I can't update the Turkish version.
> Update MusicBrainz deletion mechanism

- _data/sites.json
Opening as a draft PR as I've only just submitted this request and don't have confirmation yet that my account has been (or will be) deleted.
> Update Photobucket deletion information

- _data/sites.json
- Added Coub
- Added Terracycle
- Added Icontem
- Updated Chess.com's url, difficulty and notes. Removed notes translation.
- Removed PHP Classes
- Icontem accounts are used to log into PHP Classes (and JS Classes), which has been added.
> Add Coub, TerraCycle, Icontem, update Chess.com, remove PHP Classes

- _data/sites.json
Existing link is no longer active
> Update UPS link

- _data/sites.json
Site no longer exists (everything was moved to github discussions)
> Remove NPM Community

- _data/sites.json
- Changed existing walmart entry to walmart canada
- Remade walmart.com entry with updated information
> Add walmart.ca as hard and update walmart.com

- _data/sites.json
As far as I know, rebuy is an entirely german company, so I only added a german note.
> Add rebuy.de as easy

- _data/trans/pt_pt.json
I missed some very minor errors to translation in my first review, this fixes it.
> Very minor tweaks to pt-PT

- _data/sites.json
- Changed wording to point out that a transaction id is required in all cases (mojang accounts)
- Added process for profiles linked to microsoft accounts
> Update Minecraft steps

- _data/sites.json
The direct link for the dhl.de form doesn't work unless you view the privacy policy first (for some reason...)
> Update DHL.de and add Deutsche Post

- _data/sites.json
You have to email Boots Viewpoint to delete your account. Email address included in entry.
> feat: added Boots Viewpoint as hard

- _data/sites.json
Added NutraCheck as hard, noted email address to speak to them.
> feat: added NutraCheck as hard

- _data/sites.json
Added lenstore with link to contact page.
> feat: added Lenstore as hard

- _data/sites.json
Added coinapp.co as hard. Included URL to site to raise a support ticket
> feat: added coinapp.co as hard

- _data/sites.json
Updated the ankiapp URL. join.ankiapp was no longer functional however ankiapp.com is. Please reject PR if this is not the correct process for updating :)
> chore: corrected ankiapp URL

- _data/sites.json
Added BeyondMenu as easy as per @hippopotamusgoldfish issue #1131
> feat: add beyondmenu as easy

- _data/sites.json
- Added Icedrive
- Added Sync.com
- Added GasBuddy
- I submitted a ticket requesting my account to be deleted over a month ago and got no response. My account is still active. I didn't try requesting deletion under the CCPA as I'm not willing to submit any personal information. I set the difficulty to hard since account deletion may be possible for California residents.
- Added Prusa
-  Sending an account deletion request to the email included in their privacy policy (info@prusa3d.com) resulted in no response after a month.
- Added Castbox
- Updated Font Awesome's name
> Add Icedrive, Sync.com, GasBuddy, Prusa, Castbox, update Font Awesome

- _data/sites.json
[The site was completely shut down on Jan 24, 2022](https://www.reddit.com/r/secretsanta/comments/sbwvxa/its_done_redditgifts_has_been_shutdown_going_to/)
> Remove RedditGifts

- _data/sites.json
I have added and updated several websites to the json file, i validated it taking into account the contribution guidelines, however i haven't been able to run the project locally to make sure it actually works.
> Add and update several services

- _data/sites.json
> Close #1666: Add wappalyzer as easy

- _data/sites.json
> Close #1165: Add shop as Easy

- _data/sites.json
> Add kijiji

- _data/sites.json
> Add airmiles as hard

- _data/sites.json
This is a Norwegian "Yellow Pages" website. Very easy way to get yourself doxxed. Worst part is, it's hard to get your info off of there
> Add Gule Sider as impossible

- _data/sites.json
If this pull request goes through, the Turkish translation will need to be adjusted accordingly.
> Update Zynga to medium

- _data/sites.json
Arlo provides security cameras and cloud video storage of camera footage.
> Add Arlo as medium and AZMVDNOW.gov as impossible

- _data/sites.json
> Added fauna.com

- _data/sites.json
Seems like you don't have to contact them trough e-mail anymore.
> Update mediafire service

- _data/sites.json
> updated Instructables

- _data/sites.json
- Udacity changed the process for deleting accounts. Instructions, URL, and domains have been updated accordingly.
- Removed the Turkish translation since it's outdated now.
> Changed instructions for Udacity

- _data/sites.json
[Shut down on June 2022](https://twitter.com/GittiGidiyor/status/1538793099081785345?cxt=HHwWgoC92faK8toqAAAA)
> Remove GittiGidiyor

- _data/sites.json
[Bought and incorporated by CDON](https://www.sweclockers.com/nyhet/33039-discshop-gar-i-graven-cdon-festar-pa-resterna)
> Remove discshop.fi

- .github/ISSUE_TEMPLATE/new_entry.md
- .github/ISSUE_TEMPLATE/update_entry.md
I have update and adjusted the issue templates to be more informational correct and the template layouts have been tidied up.
> Small readability improvements on issue templates

- _data/sites.json
> Update ProMods to Hard

- _data/sites.json
They now allow everyone to delete their data
> Change PayPal to medium

- _data/sites.json
Created new pull request for Dollskill as per topascoal's suggested edits as 'hard'. Also, added Rebelsmarket as 'easy'.
> Add Dollskill and Rebelsmarket

- _data/sites.json
> Add Dunkin' Donuts

- _data/sites.json
Listed as 'hard'. Had to email support and there was no confirmation email. Had to log into the site to verify that it was closed.
> Add Tragicbeautiful.com

- _data/sites.json
The customer support form is now exclusively for ticket and login issues
> Update ticketmaster link

- _data/sites.json
They now make you select your state of residence, and as usual they still don't bother checking.
> Update Walmart instructions

- _data/sites.json
Requires a mobile device to complete, but you also need a mobile device to sign up at all.
> Add Even as easy

- _data/sites.json
I'm aware it says "close" but it warns that you will lose access to everything on the account and must sign up again later, which implies it is deleted.
> Add Roku as medium

- _data/sites.json
I'm not sure but should I change difficulty to impossible?
> Add CoderByte as hard

- _data/sites.json
Changes in this PR
-
Added 6 services:
- GeoGuessr
- GolfGameBook
- GG2U
- HitFilm
- HRK Game
- Toluna
> Added GeoGuessr, GolfGameBook, GG2U, HitFilm, HRK Game, Toluna

- _data/sites.json
Filling out the form now automatically disables your account after submission and autodeletes it after about a week - based off of my guessing, although a human still responds at some point after.
> Update Peacock notes

- _data/sites.json
There is a separate dashboard for users outside of the U.S. and Canada.
> Add Groupon international site and change Groupon to easy

- _data/sites.json
Acceptd: medium
Genius: hard
LOBSTR: medium
PlanetMinecraft: hard
WorldAnvil: easy
Also updated the notes for Quora. Added a bit about how it takes 14 days for Quora to delete your account, and if you log back in any time during those 14 days, the deletion process is canceled
> Add Acceptd, Genius, LOBSTR, PlanetMinecraft, and WorldAnvil. Update Quora

- _data/sites.json
> Add targetjobs as easy

- _data/sites.json
Adding Kwai (medium) and Padrim (impossible).
> Adding Kwai and Padrim

- _data/sites.json
Added 3 new sites. AllDebrid, Nexo, Sendspace.
> Added AllDebrid, Nexo, and Sendspace

- _data/sites.json
I made some errors and i fixed them _dafont name updated_ is the correct commit
> Add DaFONT as hard

- _data/sites.json
Added Oculus VR (easy), Rue du Commerce (impossible) and Rumble (hard). And put Tiktok and Spotify as a popular sites. They're a popular sites, right?
> Added Oculus VR, Rue du Commerce and Rumble.

- _data/sites.json
More exactly, Nube and Proofwiki (both impossible), Gettr and XVideos (both easy) and Curriculum and TicketWeb (both hard).
> Add Curriculum, Gettr, Nube, Proofwiki, TicketWeb, XVideos

- _data/sites.json
No contact with customer service is required, and link is now direct
> Update Uber link and difficulty

- _data/sites.json
Thanks for the Chrome extension 💖
> Add Python Morsels as easy

- _data/sites.json
Added The Guardian, Apoia.se (both hard) and Uncyclopedia (impossible).
> Add The Guardian, Apoia.se and Uncyclopedia

- _data/sites.json
Adding 1fichier (hard) and Journal du Geek (easy) and removing Vive, finished in 2019 - https://en.wikipedia.org/wiki/Vine_(service)
> Add 1fichier and Journal du geek and remove Vine

- _data/sites.json
I attempted to delete my account on 9/6/22 and they have never responded and I can still log into the account.
> Add kistania.com as impossible

- _data/sites.json
BorgBase is offsite backup provider that contributes to BorgBackup
> Add BorgBase as easy

- _data/sites.json
All of them start with "H" and are easy.
> Add HeadHunter, hide.me, Holiday Pirates and Hype Machine

- _data/sites.json
> Add Spanish notes to Uber

- _data/sites.json
> Add Infinity Free

- _data/sites.json
Penpot is fairly new open source app designing tool
> Add Penpot as easy

- _data/sites.json
> Fix the link for wikipedia

- _data/sites.json
- Domains taken from linked privacy policy
- Email content taken from [ICO template](https://ico.org.uk/your-data-matters/your-right-to-get-your-data-deleted/)
There's probably some scope in the project to introduce a way of deduplicating email content for common requests such as GDPR.
> Add Stardock as limited

- _data/sites.json
> Add Kattis as hard

- _data/sites.json
Adding another item to the list!
> Add Privacy to the list as hard

- _data/sites.json
I added this site https://insights.gg/
> Add Insights as easy

- _data/sites.json
[added various relevant subdomains and country/language specific domains](https://github.com/jdm-contrib/jdm/commit/8422736341a488643a02a745049fe1cb761c1722)
* added language/country specific domains for `Google`, `Kaspersky`, `Wikipedia` and  `Audible`
* added relevant subdomains for many services
* also did [this](https://github.com/jdm-contrib/jdm/commit/d134f4f81f6af99464a2b29ac25244f9f0860e3e#commitcomment-86189540)
> Add various subdomains and country/language specific domains

- _data/sites.json
* added the following Google Services similar to `Blogger`, `Gmail` and `YouTube`: `Google One` and `Google Pay`
* added reference to `Google` to the following Google Services: `Blogger`, `Gmail`, `YouTube`, `Google One` and `Google Pay`
* changed `YouTube` difficulty to `medium`, because it requires a confirmation email
* added domains `google.co.uk` and `takeout.google.com` to `Google`
> Change/add various Google Services

- _data/sites.json
Brilliant is online interactive learning tool
AgoraDesk is Bitcoin and Monero exchange.
Sorry but somehow both ended in single PR.
> Add Brilliant and AgoraDesk as easy

- _data/sites.json
added reference to Microsoft Account to Skype (Skype Account can't be deleted without deleting Microsoft Account)
> Add reference to Microsoft Account to Skype

- _data/sites.json
* merged already existing `ProtonMail` and `ProtonVPN` to `Proton`, added some subdomains
* added subdomains for missing services `ProtonDrive` and `ProtonCalender` to `Proton`
* changed difficulty of `Proton` to `medium`, because it requires selecting a reason and giving a short feedback
> Merge all Proton products

- _data/sites.json
Added various microsoft subdomains.
> Add Microsoft subdomains

- _data/sites.json
added `music.youtube.com` and `studio.youtube.com` to YouTube
> Add YouTube Music and YouTube Creator Studio subdomains

- _data/sites.json
A self explanatory page, no special instructions needed.
> Add Gradcracker as easy

- _data/sites.json
> Add Stan as impossible

- _data/sites.json
Render.com is CDN network to deploy static sites automatically from Git repositories.
I cannot provide url for deletion, because url is not the same for every user (but the interface is).
> Add Render as easy

- _data/sites.json
I added the KDE Bugtracking system and put the reddit link since i couldn't find any other source saying that it was necesary to e-mail the sysadming to delete an account on the Bugtracker
> Add KDE Bugtracking System as hard

- _data/sites.json
Information: https://cvonline.me/en/support/accounts/removing-account
> Add CV online as hard

- _data/sites.json
They no longer requiring emailing support unless you want a data export or need to wipe an entire organization and its users
> Change ClickUp to easy

- _data/sites.json
It actually removes everything despite it saying "deactivate"
> Add Displate as easy

- _data/sites.json
App was completely redone and they now have a proper help center
> Update BeReal notes and link

- _data/sites.json
Addition of a new site, 7plus.
Difficulty medium due to a form submission being needed, and having to find it on a support site.
> Add 7plus and Fanatical as hard

- _data/sites.json
> Add All 4 / Channel 4 as easy

- _data/sites.json
> Add CDKeys as easy

- _data/sites.json
> Add CryptoVoucher as easy

- _data/sites.json
> Add Depop as hard

- _data/sites.json
> Add DWService as easy

- _data/sites.json
> Update Pixilart to easy

- _data/sites.json
* Added YUR as limited
* Added Splice as easy
* Added cgtrader as hard
> Add YUR, Splice and cgtrader

- _data/sites.json
- Add Busuu as easy
- Add Mine as easy
- Update Sololearn to easy
> add Busuu, Mine. update Sololearn

- _data/sites.json
Add DelugeRPG as impossible and Packt as hard
> Add DelugeRPG and Packt

- _data/sites.json
Glovo link no longer works, only the app seems to have a support section. I rewrote the English text per the changed routine.
> Update Glovo instructions

- _data/sites.json
- Add Mimo as easy
- Add Trustpilot as easy
- Add Appypie as easy
- Add Hostinger as easy 
- Add TubeBuddy as easy
- Add AVG as easy
- Add Studio as easy
- Add Tubi
- Update Pixlr
> Add mimo, trustpilot, appypie, hostinger, tubebuddy, avg, studio, tubi. update pixlr

- _data/sites.json
Added Wacom (easy), Wilson epark (hard), Whirlpool (impossible) and removed MePergunte, that no longer exists and the link redirects to another page.
> Adding Wacom, Whirlpool, Wilson epark and remove MePergunte

- _includes/body.html
Not filtering for special characters right now, since there is only 1 entry and it's the very first.
> Close #1456: Add button to allow for digit filter

- _data/sites.json
uses Microsoft Account (same process)
> Remove Outlook

- _data/sites.json
Merged `Groupon (International)` and `Groupon (US/Canada)`
> Merge Groupon variants

- _data/sites.json
`meta` always after `name` (related to #1460)
> Standardize meta

- _data/sites.json
I don't believe in myself anymore
> Add Wilds.io, Shinden, Lampyre and Bato.to as easy

- _data/sites.json
Rumble apparently recently added a delete button at the bottom of the profile settings.
> Update Rumble (easy)

- _data/sites.json
Adding Nicequest and Fooducate (both of them easy).
> Add Nicequest and Fooducate as easy

- _data/sites.json
Ngrok account deletion process seems to have changed
> Update ngrok url and notes

- _data/sites.json
Hetzner is cloud services provider
> Add Hetzner as easy

- _data/sites.json
> Add DJI as medium

- _data/sites.json
The latest company to move to OneTrust
> Update T-Mobile link

- _data/sites.json
Add WP (Wirtualna Polska and WP Poczta) as easy with provided link to account's settings. Add notes in english and polish.
> Add WP as easy

- _data/sites.json
URL: https://www.oracle.com/legal/data-privacy-inquiry-form.html
difficulty: hard
notes: You have to send a privacy inquiry to get your data deleted. (It can take a few days)
> Add Oracle as hard

- _data/sites.json
- Add Jetbrains Academy (Hyperskill) as easy
- Add TunnelBear as easy
> Add Jetbrains Academy, TunnelBear

- _data/sites.json
> Add TextNow as easy

- _data/sites.json
Adding Pixel Starships and the popular and scary OpenAI (both of them hard).
> Adding Pixel Starships and OpenAI as hard

- _data/sites.json
Adding ALDO, Agoda and another AI solution Rytr (hard) and Ancestry (easy).
> Add ALDO, Agoda, Ancestry and Rytr

- _data/sites.json
Add Game Tracker, RedBooth, RedFin and SyncFusion (all of them easy).
> Add Game Tracker, RedBooth, RedFin and SyncFusion as easy

- _data/sites.json
Add Todo Cloud as hard, with notes in English and Italian.
> Add Todo Cloud as hard

- _data/sites.json
name: "Nexon",
url: "https://support.nexon.net/hc/en-us/articles/360001112943-How-can-I-delete-or-deactivate-my-account-",
difficulty: "impossible",
notes: "The support page tells you to open a ticket but you can't open a ticket to delete your account",
domains:
"nexon.com",
"one.nexon.com",
"nexon.net",
"support.nexon.net"
> Add Nexon as impossible

- _data/sites.json
> Add McDonald's as easy

- _data/sites.json
(I know that EA Origin already exists but these are different accounts.)
> Add EA as hard

- _data/sites.json
Specify that usernames of deleted accounts of AnonAddy cannot be reused and translate into Italian AnonAddy notes.
> Specify that usernames of deleted accounts of AnonAddy cannot be reused

- _data/sites.json
After digging through the faq of both sites, I found actual forms for them. Neither of them ask for location or actually say it's limited to European users so for now these should be hard.
> Update Stardock and YUR.fit to hard

- _data/sites.json
Add AddMeFast, Archipad, Plus500, Sfimg and SurfEasy.
> Add AddMeFast, Archipad, Plus500, Sfimg and SurfEasy

- assets/css/style.css
In #1537, I removed the font-weight from the wrong object. This one should fix the problem though.
> Remove font-weight from button to improve accessibility (again)

- _data/sites.json
> Add HiNative as easy

- _data/sites.json
> Add Kanji Koohii as easy

- _data/sites.json
> Update Facebook Messenger to easy

- _data/sites.json
Account system is separate from normal tiktok
> Add TikTok Developer as hard

- CONTRIBUTING.md
[The Add-on seems to also use the domains array.](https://github.com/search?q=repo%3Ajdm-contrib%2Fjustdelete.me-firefox-addon%20domains&type=code)
> Add Firefox Add-on mention

- _data/sites.json
**What's new:**
I added the site [Smodin.io](url)
> Add Smodin as easy

- _data/sites.json
> Fix multiple links with broken ping

- _data/sites.json
- Added FeedBin
- Added LanguageTool
- Added Guildtag
- I was on the fence whether this should be marked as medium or not, but I figured that most users seeking to have their account deleted probably want their posts gone too.
- Updated IMDb's URL
- Updated Osu!'s URL
- Updated Issuu's name, URL, and notes
- Updated Bookmark OS's URL, difficuly, and notes. Removed note translation. Added an email address.
> Add FeedBin, LanguageTool, Guildtag, update IMDb, Osu!, Issuu, Bookmark OS

- _data/sites.json
- Added Flo Health
- Added My Calendar
- Added BabyCenter
- Updated Shop Your Way's URL, difficulty, and notes.
- Shop Your Way has redesigned their website and removed the page allowing you to delete your account yourself.
- Deleting your account now cancels your in-store rewards membership.
> Add Flo Health, My Calendar, BabyCenter, update Shop Your Way

- _data/sites.json
Currently linked page has been removed from xda.So i have updated the link with direct form url. Also i've updated the descriptions in English and translated into other languages
> Updated the link and description for XDA Developers

- _data/sites.json
I aded tvtropes as easy based on issue #1691 informations
> Added tv-tropes as easy that fixes #1691

- _data/sites.json
This pull request adds the service "Storj" with the hard difficulty.
> add Storj as hard

- _data/sites.json
Added virustotal (virustotal.com)
> Add virustotal as easy

- _data/sites.json
Changed:
- Chegg.com
Added:
- Dataquest.io
- Lemehost.com
- Mashable.com
- Nutaku.net
- Parallels.com
- Server.pro
- Telltale.com
- TuneMyMusic.com
> Add 8 entries and Update 1 entry

- _data/sites.json
- Added Foodmaxx
- Corrected Guildtag's URL
- Removed FaucetHub
- [FaucetHub shut down in December 2019](https://web.archive.org/web/20191227180221/https://faucethub.io/news/post/211)
> Add Foodmaxx, update Guildtag, remove FaucetHub

- _data/sites.json
Added OmaPosti and Verkkokauppa.com
> Add OmaPosti and Verkkokauppa.com

- _data/sites.json
Update various games by Riot Games
**Updated:**
* League of Legends
* Riot Games
**Added:**
* Valorant
* League of Legends: Wild Rift
* Legends of Runeterra
closes #1711
> Update Riot Games

- _data/sites.json
https://www.lingvano.com/asl/
https://help-asl.lingvano.com/support/solutions/articles/101000365040-how-can-i-delete-my-account-
> Add deletion of the Lingvano account

- _data/sites.json
> Add CubieCloud (Fixed)

- _data/sites.json
- Add Alipay as medium
- Add Baidu as medium
- Add Bilibili as medium
- Change QQ as medium
- Add notes for QQ
- Update url for QQ (The former is Wechat one, not QQ.)
- Change Wechat as medium
- Add notes for Wechat
- Add Zhihu as easy
- Add Weibo as medium
- Add Elsevier.com as hard
> Add Alipay, Baidu, Bilibili and Zhihu websites:

- _data/sites.json
- Add ChangeIP as hard
- Add Immomio as easy
- Add Immowelt as easy
- Add Zotero as easy
Also remove some superfluous whitespace.
> Add ChangeIP, Immomio, Immowelt, and Zotero

- _data/sites.json
> Update Pocket Casts to easy

- _data/sites.json
adding instructions for https://www.headshotgenerator.io/
> adding HeadshotGenerator

- _data/trans/pt_br.json
Fixes and improvements in the translation to pt-BR
> Fix translation for pt-br

- _data/sites.json
Link directly to the correct lutris page and shorten description
> Improve lutris link and description

- _data/sites.json
> Update Algor Education

- _data/sites.json
The app and the website version have two independent registration systems, so I think there should be two entries.
> Update Cash'em All and Add Cash'em All Web

- _data/sites.json
> Add IBMid as hard

- _data/sites.json
> Add Joom as easy

- _data/sites.json
> Add FitnessSyncer as easy

- _data/sites.json
* Add Genymotion Desktop as easy
* Add Genymotion Cloud as hard
This closes #1814.
> Add Genymotion

- _data/sites.json
This PR adds data for the webpage [Dictionary.com](https://www.dictionary.com)
> Add data for Dictionary.com

- _data/sites.json
This PR adds information on how to delete a shotgun.live account
> Add shotgun.live information

- _data/sites.json
> Microsoft Account and Microsoft Office 365 (now Microsoft 365) are the same account.

- _data/sites.json
"eBay Kleinanzeigen" is now known as "Kleinanzeigen"
> Add Kleinanzeigen as easy

- _data/sites.json
I couldn't find any mention of how to delete an account anywhere on their website/docs/community, so I contacted them. They gave me this email to delete an account:
As I couldn't find anything better, the `url` simply is their privacy policy. It mentions the right to delete your data.
`notes` copied from @WebSnke (#1841)
> Add ILLA as hard

- _data/sites.json
> Add MinID as hard

- _data/sites.json
Adds [Cocoleech](https://cocoleech.com/about) as easy to delete.
> Add Cocoleech

- _data/sites.json
> Update Rakuten to Limited

- _data/sites.json
> Split Groupon US and Worldwide

- _data/sites.json
> Added Interrail.eu

- _data/sites.json
Added NS (Nederlandse Spoorwegen)
> Added NS (Nederlandse Spoorwegen)

- _data/sites.json
> Added Bleep

- _data/sites.json
Changes 'remove' to 'delete' and added notes in Dutch
> updated Crowdin entry

- _data/sites.json
Added Marktplaats
https://www.marktplaats.nl/
> Added Marktplaats

- _data/sites.json
Added Zamnesia as hard
https://www.zamnesia.com/
> Added Zamnesia as hard

- _data/sites.json
Added OV-chipkaart
https://www.ov-chipkaart.nl/en
> Added OV-chipkaart

- _data/sites.json
- Added NovelAI (closes #1862)
- Added Teladoc (closes #1863)
- Added Zaxby's (closes #1864)
- Added Capsule (closes #1865)
- Added Aquaillumination (closes #1866)
- Added Overwolf (closes #1867)
- Added KBDfans (closes #1868)
- Updated Fanatical's url, difficulty, note, and domains
- Updated AnonAddy's name, url, note, and domains
- [AnonAddy has changed it's name to addy.io](https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/)
- Removed duplicate notes_it note from Algor Education (closes #1847)
> Add NovelAI, Teladoc, Zaxby's, Capsule, Aquaillumination, Overwolf, KBDfans, update Fanatical, AnonAddy

- _data/sites.json
Added Epik as hard
https://www.epik.com/
> Added Epik as hard

- _data/sites.json
Added Wordfeud as easy
https://wordfeud.com/
https://en.wikipedia.org/wiki/Wordfeud
> Added Wordfeud as easy

- _data/sites.json
> Add lidraughts as easy

- _data/sites.json
Adds [Emby](https://emby.media) as easy to delete.
> Add Emby as easy

- _data/sites.json
Adds [npm](https://www.npmjs.com/) as easy to delete.
> Add npm as Easy

- _data/sites.json
https://beta.character.ai/settings/
Scroll to the bottom of the settings page on your profile and click ”Remove Account“, then insert your username and choose whether you want to export your data while deleting it or not.
> Add Character.Ai as Easy

- _data/sites.json
> Remove EDDB and Gyfcat

- _data/sites.json
All of these previously returned 404/something similar in the `ping_websites` workflow.
> Update various services

- _data/sites.json
Updates the note for IFTTT to mention that one might wanna remove their connected services.
> Update notes for IFTTT

- _data/sites.json
Adds [Genesis Cloud](https://www.genesiscloud.com/) as easy to delete.
> Add Genesis Cloud as easy

- _data/sites.json
> Add TruthFinder as easy

- _data/sites.json
Adds [Magasin](https://www.magasin.dk) as easy to delete.
> Add Magasin

- _data/sites.json
Adds [Lifesum](https://lifesum.com) as easy to delete.
> Add Lifesum

- _data/sites.json
Specify that if you delete your account, you will not be able to reuse the same email address to reopen a new account.
> Update Apple ID / iTunes

- _data/sites.json
Adds [TinyLetter](https://tinyletter.com/) as easy to delete.
> Add TinyLetter

- _data/sites.json
Add SitePoint as impossible to delete.
> Add SitePoint

- _data/sites.json
There was additional information regarding NationStates account deletion that I forgot to add. This pull request adds these changes.
> Additional info regarding NationStates

- _data/sites.json
Add [Litmus](https://www.litmus.com/) as limited.
There's an option to disassociate one's account from the email address used which they refer to as "simple deletion", however, I don't consider that a deletion.
> Add Litmus

- _data/sites.json
Add [Visualping](https://visualping.io/) as having "limited" account deletion.
I wasn't asked to show any proof of living in a location with privacy rights.
> Add Visualping

- _data/sites.json
Add [Redirect.ing](https://redirect.ing) as easy to delete.
> Add Redirect.ing

- _data/sites.json
Site requires the user to contact support through a form to delete their account, so the difficulty has been set to "hard". The provided URL leads to the support article on deleting accounts.
> Added new site, "Epidemic Sound"

- _data/sites.json
According to @clicky6 the link is working again
> Update Crunchyroll back to easy

- .github/ISSUE_TEMPLATE/new_entry.md
- CONTRIBUTING.md
- _data/trans/ar.json
- _data/trans/cat.json
- _data/trans/cz.json
- _data/trans/de.json
- _data/trans/en.json
- _data/trans/es.json
- _data/trans/fa.json
- _data/trans/fr.json
- _data/trans/gr.json
- _data/trans/id.json
- _data/trans/it.json
- _data/trans/kr.json
- _data/trans/nl.json
- _data/trans/pl.json
- _data/trans/pt_br.json
- _data/trans/pt_pt.json
- _data/trans/ro.json
- _data/trans/ru.json
- _data/trans/sk.json
- _data/trans/sr.json
- _data/trans/th.json
- _data/trans/tr.json
- _data/trans/ua.json
- _data/trans/vi.json
- _data/trans/zh-cn.json
- _data/trans/zh-tw.json
- _includes/body.html
Fixes https://github.com/jdm-contrib/jdm/issues/1772
Related URLs:
- https://github.com/fregante/jdm
- https://chrome.google.com/webstore/detail/just-delete-me/dlhckcablohllindinahbbpnfgblimoe
> Update chrome extension URL

- CONTRIBUTING.md
- TRANSLATION_REFERENCE.md
Modify CONTRIBUTING guide to refer people to the new Crowdin integration for easier translation of the website
> Add guide to use Crowdin as translator tool

- _data/sites.json
> Add VidIQ as hard

- _data/sites.json
Thank you for a great site to assist with managing digital footprint, here is my contribution.
Website: [solo.to](https://solo.to)
Difficulty: easy
> Add solo.to as easy

- _data/sites.json
Thanks for this project! I'm the creator of this site ([turboscribe.ai](https://turboscribe.ai)) and wanted to add it to this awesome directory.
> Add turboscribe.ai as "easy"

- _data/sites.json
- updated direct link for AOL
- added new note for Yahoo & AOL
- added new entry for Vivo
closes #1962, #1964
> Update AOL, Yahoo & Vivo

- _data/sites.json
> Add Archive of Our Own as easy

- _data/sites.json
Fiverr now provides an easy way to delete accounts.
> Update fiverr to easy

- _data/sites.json
Adding NameMC.com to the sites list.
> NameMC Site Addition

- _data/sites.json
> Add Cutout as easy

- _data/sites.json
> Add sdc.com as easy

- _data/sites.json
Add Author.today (as impossible), Bubbl.us (as hard), Shikimori (as impossible) & TapTap (as easy).
Notes languages: en & ru.
> Add Author.today, Bubbl.us, Shikimori & TapTap

- _data/sites.json
Add Computeruniverse (as hard), iLoveIMG (as hard), iLovePDF (as hard), Flathub (as easy) & Reverso (as hard)
Notes languages: en & ru
P.S.: Separated iLoveIMG and iLovePDF 'cause of different domains and contact forms. Not sure if the accounts are shared, tho.
> Add Computeruniverse, iLoveIMG, iLovePDF, Flathub & Reverso

- _data/sites.json
> Update Flathub domains

- _data/sites.json
Add text.ru (as easy), WOT (as easy) & Lingualeo (as medium)
Notes languages: en & ru; except for text.ru (only ru)
> Add text.ru, WOT & Lingualeo

- _data/sites.json
Added entries for Clipchamp, Krafton (for PUBG and other games), and Mobalytics.
> Add Clipchamp, Krafton, and Mobalytics as easy

- _data/sites.json
> Add Z-Library as medium

- _data/sites.json
> Update Internet Archive to medium

- _data/sites.json
Added "MakeMyTrip"  as easy and "Hotstar" as medium.
> Add MakeMyTrip and Hotstar

- _data/sites.json
> Update TickTick url

- _data/sites.json
> Add ICANN as easy

- _data/sites.json
addresses open issues #2037 and #2038
> Add distill.io and Bingx

- _data/sites.json
* Add Chocolatey (as hard)
* Fix small errors in notes_ru for iLoveIMG & iLovePDF
> Add Chocolatey; Fix iLoveIMG & iLovePDF

- _data/sites.json
> Add Temu.com

- _data/sites.json
Updated link from core domain to account settings page where delete button is located
> Update Coursera URL

- _data/sites.json
Padrim will shutdown on May 30th.
> Remove Padrim.

- _data/sites.json
> Add Stackhero as hard (#2051)

- _data/sites.json
> Add Phind as easy

- _data/sites.json
> Add V.PS Hosting as easy

- _data/sites.json
> Add Auchan as hard

- _data/sites.json
Per <https://help.antisoftware.club/support/solutions/articles/62000225460-how-do-i-delete-a-page-my-account->.
> Add Cohost as hard

- _data/sites.json
> Update galaxy to medium

- _data/sites.json
added minehut 
<details><summary>code</summary>
<p>
{
"name": "Minehut",
"url": "https://app.minehut.com/support/form",
"difficulty": "hard",
"notes": "The only way to contact them is at https://app.minehut.com/support/form and https://support.minehut.com/hc/en-us/requests/new.",
"domains": [
"minehut.com",
"app.minehut.com",
"support.minehut.com"
]
},
</p>
</details>
> Add Minehut as hard

- _data/sites.json
Closes #2072, #2076, #2079, #2080, #2082, #2083
> Add Pionex, Featurebase, Cronometer, Cracker Barrel, Chewy BuiltyByBit

- _data/sites.json
> Update Perplexity to easy

- _data/sites.json
> Add Scite_ as hard

- _data/sites.json
> Add commiss.io as impossible

- _data/sites.json
This PR adds Terraform Cloud ([official support document](https://support.hashicorp.com/hc/en-us/articles/1500002617421-Deleting-Terraform-Cloud-Accounts)).
> Add Terraform Cloud as hard

- _data/sites.json
Closes #2098
Closes #2096
Closes #2097
> Add KBin, Natural Readers, Fixer.io

- _data/sites.json
Old url was dead and redirects to support homepage
> Update Whatsapp url

- _data/sites.json
I linked the support page and not the deletion page as I don't have an account so I cannot access it.
> Add SNCF as easy

- _data/sites.json
Hey,
I just added a new site, `wifimap.io` as this was not on justdelete.me.
Written by my own experience.
Thanks for the site btw!
> Add wifimap.io as easy

- _data/sites.json
> Add Whimsical as easy

- _data/sites.json
> Add FlokiNET as hard and Seedbox as easy

- _data/sites.json
moved current url to url_fr and set an english url
> Update SNCF localization

- _data/sites.json
They added a button to close the account but require to contact them to actually delete everything
> Update remitly to medium

- _data/sites.json
Mon Compte Formation -> easy
Ameli -> Easy
Mon Espace Santé -> Easy
Mes Services Étudiant -> Hard
impots.gouv.fr -> Hard
data.gouv.fr -> easy
France Identité -> Medium
La Poste -> Hard
L'identité Numérique La Poste -> Medium
YRIS -> Medium
Pix -> Hard
Pass Culture -> Easy
CNIL -> Hard
Agence nationale des titres sécurisés -> easy
Service-Public.fr -> easy
> Add multiple public French services

- _data/sites.json
Closes #2129
Closes #2128
Closes #2127
Closes #2126
> Add SteelSeries, youlookfab, W3Schools and update LogMeIn + TeeSpring

- _data/sites.json
Linked the [settings page](https://www.badlion.net/settings)
> Add Badlion as easy

- _data/sites.json
> Add uVPN as hard

- _data/sites.json
> Add adidas.com as easy

- _data/sites.json
> Add Exclusive Car Registry as easy

- _data/sites.json
> add alza and czc as easy

- _data/sites.json
Hey there!
I noticed that the [umami.is](http://umami.is/) website is not present in the list, so I have added it. I hope this small contribution will help!
> Add umami as easy

- _data/sites.json
Hey there!
After trying to delete my account on their website, I have added the [Hemingway Editor](https://hemingwayapp.com/) into the list. I hope this is useful!
> Add Hemingway Editor as hard

- _data/sites.json
Access `infinityfree.net` now will auto redirect to `infinityfree.com`
ref delete section:
> Update note for infinityfree

- _data/sites.json
[CEEOL request](https://github.com/jdm-contrib/jdm/issues/2160)
> add CEEOL, Ngan Luong, Nulled as impossible

- _data/sites.json
There are rare countries where discord is banned, preventing from deleting the account, that's why I set it to limited.
> Add themeplaza as limited

- _data/sites.json
> Update Alibaba deletion instructions

- _data/sites.json
> Add ArchLinux accounts

- _data/sites.json
> Add Filen.io as easy

- _data/sites.json
> Add Qobuz as easy

- _data/sites.json
Updated the difficulty of CoinMarketCap from hard to easy as they now provide a simple solution to automatically request account deletion.
> Updated CoinMarketCap to easy

- _data/sites.json
Updated Twitter's information to reflect the rebranding to X done on May 17, 2024.
> Update Twitter name

- _data/sites.json
I wasn't able to find a delete button in the account tab, so I wrote to them, and a day later, I received confirmation that my
data had been deleted.
I therefore marked it as hard, as it would be in line with the contribution notes. However, I could also argue that it's more like
medium, as it wasn't difficult at all-just writing an email and receiving confirmation.
> Add amso as hard

- _data/sites.json
The account is only managed in the app, so I don't know if there is anything else to do, or if I should keep the website in the data
> Add Plexus as easy

- _data/sites.json
May actually be limited difficulty instead, needs verification.
> Add Langfuse as hard

- _data/sites.json
Added Brandpad as easy
Added Builder.io as hard
Added CoffeeCup as hard
Added Copyleaks as Medium
Updated DigitalOcean as the current url takes me to nothing
> Add Brandpad, Builder.io, CoffeeCup, Copyleaks and update DigitalOcean

- _data/sites.json
> Update Avito URL

- _data/sites.json
add domains for new services Proton Pass and Proton Wallet
> Update Proton domains

- _data/sites.json
Updated Glassdoor difficulty to hard to reflect the non-automated process for account deletion.
> Update glassdoor to hard

- _data/sites.json
Hey there!
Since [Yuka](https://yuka.io/) is not included in the list, I had inserted it in.
I hope this humble contribution will help!
> Add Yuka as easy

- _data/sites.json
> Update M Réso / Appli M

- _data/sites.json
Updated Wordpress.org to easy to reflect the fully automated account deletion process.
> Update wordpress.org to easy

- _data/sites.json
Updated to medium to reflect the need to delete active subscriptions to make account deletion possible.
> Update Wordpress.com to medium

- _data/sites.json
> Add Cursor as easy

- _data/sites.json
I added LuminPDF site as easy URL: https://www.luminpdf.com/
> Add LuminPDF as easy

- _data/sites.json
Added [back4app](https://www.back4app.com/) account deletion instructions, and a link to the relevant Help article.
> Add back4app as hard

- _data/sites.json
Yesterday had an experience of asking TLauncher administration to delete my account(they eventually deleted it). I would like to add some useful information to the notes, and additionally provide a Russian translation for them.
> Update TLauncher to limited

- _data/sites.json
> Update ASUS to easy

- _data/sites.json
> Add Iceland and Glide as hard

- _data/sites.json
Accounts appear to be able to be deleted easily by yourself now
> Update Cohost to easy

- _data/sites.json
> Add Addicting Games as hard

- _data/sites.json
Hey there! 👋
I had submitted a yet another entry to the list, this time the [MAGIX](https://www.magix.com/) website.
Cheers!
> Add MAGIX as hard

- _data/sites.json
Confirmed account deletion instructions at [TP-Link's official doc](https://www.tp-link.com/us/support/faq/2629/). The flow is a bit convoluted, but fairly straightforward to complete. Not sure if the Notes here need so much detail, but I decided to be thorough for now lol.
> Add TP-Link Cloud as easy

- _data/sites.json
Website is closing down soon so can probably be removed in a few months
> Add Stake as easy

- _data/sites.json
> Add OK as easy

- _data/sites.json
Despite the 2 being the same company in different countries, the process is not the same so I separated them.
Also the italian translation is made with LibreTranslate because as the company is mainly italian I thought it would be very important
> Add Trenitalia and Trenitalia France

- _data/sites.json
Hey there!
I added in the Reg.ru website, which resolves the #2287.
> Add Reg.ru as medium

- _data/sites.json
I genuinely need email_body_CODE because of the mess it is. I put it all in english but as there are 3 languages, having one at least in spanish is important
> Add Renfe as hard

- _data/sites.json
Update Shopify from impossible to hard, with new url and notes
> Update Shopify to hard

- _data/sites.json
I downloaded the list of all .sncf domain names and looked at them to find the important ones. It should be good now
> Complete, hopefully the list of SNCF Domains

- _data/sites.json
Expedia has improved their account deletion process and you no longer need to talk to an agent.
> Update Expedia to easy

- _data/sites.json
Keeping as draft for now as I'm waiting for my account deletion
> Add Cultura as hard

- _data/sites.json
I forgot to put the previous one as draft. It still works but I'm making this to be more precise. I will mark ready when my account deletion will be confirmed
> Update ETS Global

- _data/sites.json
000webhost shutted down on October 14th - https://www.hostinger.com/blog/000webhost-closes
> Remove 000webhost

- _data/sites.json
I included the site Codeium because I noticed it was missing, putting its difficulty easy, since the procedure for deleting an account is straightforward.
> Add Codeium as easy

- _data/sites.json
Fixed spelling error in RateYourMusic entry
> Fixed spelling error

- _data/sites.json
> Add Brevo as easy

- _data/sites.json
There is a button in the settings to delete the account. As it still takes time I changed from Hard to Medium
> Update LBRY Odysee

- _data/sites.json
> Update GrubHub to medium and RobinHood to impossible

- _data/sites.json
For some reason, the instructions are not documented in French, but they are in German (obviously) and in english.
> Add Deutsche Bahn as Easy

- _data/sites.json
relevant info can be found [here](https://support.gog.com/hc/en-us/articles/23125738390557-FAQ-Account-Deletion?product=gog)
> Change gog.com difficulty to easy

- _data/sites.json
Rename M Réso / Appli M and add M Covoit Lignes+ and M Réso (actual account this time)
It's a huge mess
> Update M Mobilités

- _data/sites.json
Hey there! 👋
I had created an entry to the list, this time the [The Sims Resource](https://www.thesimsresource.com) website.
Cheers!
> Add The Sims Resource as hard

- _data/sites.json
Adds account deletion instructions for:
- Augment
- GamersGate
- Gamesplanet
- WeMod
and updates some infos on:
- LG Account (mainly updating the URL to an existent one and precising that the URL may not be correct depending on the region of the user)
- Voicemod (really just adding that there may be further email confirmation needed if there's an active license)
Feel free to let me know if I missed something or didn't do this properly.
> Add Augment, GamersGate, Gamesplanet, WeMod and update two entries

- _data/sites.json
Using the new instructions I have written I was able to receive confirmation from Stan that my account would be deleted, rather than having my request refused as the previous notes suggested.
> Change Stan from Impossible to Hard

- _data/sites.json
The url for deleting instagram account changed
> Instagram change delete url

- _data/sites.json
Info on the account deletion process -> [link](https://help.uxcel.com/en/articles/4634446-can-i-delete-my-uxcel-account)
> Change Uxcel from hard to easy

- _data/sites.json
If something is wrong please let me know! :-)
> Add gamemaker

- _data/sites.json
Based on my experience deleting an applicant account. Wasn't sure if difficulty should be medium or hard. Added links for both main website and applicant website.
> Add Boeing

- _data/sites.json
According to the linked page, full account deletion is possible. I do not have a Couchsurfing account to confirm this, but I edited the difficulty and note to reflect what the support page says.
> Edit Couchsurfing difficulty and note

- _data/sites.json
Technically the same account but both websites have a different process, so left these independent. Updated Thingiverse information.
> Add MakerBot, update Thingiverse

- _data/sites.json
Unsure if this is hard or limited, currently going through the process myself. The only relevant URL I could find is the privacy policy page.
> Add zyBooks

- _data/sites.json
> Add Form.taxi as easy

- _data/sites.json
> Add Musicboard, Turismo Itaipu and SulAmerica

- _data/sites.json
> Remove 9anime

- _data/sites.json
Added instructions for German contact lens shop Lensbest with difficulty easy along with a German translation. 
Changed vrbo.com to easy, since they now provide a delete button on their account page [1].
[1]: https://www.vrbo.com/en-us/helpcenter?articleId=22910&pwaDialog=article-dialog
> Added Lensbest and changed VRBO

- _data/sites.json
Also includes a minor spelling correction in Spanish translation of the omegaUp entry.
> Add Rediff, AulaFacil, OM Personal English, Timus Online Judge, and (formerly UVa) Online Judge

- _data/sites.json
> Update Fleek to impossible

- _data/sites.json
Covers crypto exchange example of #2412.
> Add Gemini as hard

- _data/sites.json
* Add "Classy" website with medium difficulty because you have to fill out a form and wait for a response.
> Add Classy

- _data/sites.json
Added:
- iClicker.com
- hbsp.harvard.edu
- knetbooks.com
- altium.com
- gradescope.com
Updated:
- zybooks: changed email address
- cengage: changed difficulty, notes, and url
> Add several sites and update a couple

- _data/sites.json
- Added PokeMMO as hard since you have to create a support ticket to customer support
- Corrected spelling error 'contanct' to 'contact' in the notes of payback.de and points.com
> Add PokeMMO as hard, fix spelling errors

- _data/sites.json
> add ZenMarket as easy

- _data/sites.json
> Update IndieGala instructions, Add Koyeb

- _data/sites.json
Modified the Venmo URL link to the direct page with the actual delete button for faster deletion.
> Update Venmo URL

- _data/sites.json
> Add Paperless Post as easy

- _data/sites.json
- Add Volcengine as medium
- Add juejin as hard
> Add Volcengine, juejin

- _data/sites.json
> Add IGDB as easy

- _data/sites.json
> steamcommunity.com

- _data/sites.json
> Add Zenni Optical as hard

- _data/sites.json
Added wiki domains because you contact weirdgloop not wiki admins to delete info
> Add WeirdGloop as impossible

- _data/sites.json
- Add SEAGM as medium
- Add MTCGAME as impossible
- Add ENSHAN as impossible
> Add SEAGM, MTCGAME, ENSHAN

- _data/sites.json
This is just adding framework the company to the list. I hope this is sufficient, please let me know if there's any corrections, comments, or suggestions!
> Add framework to hard

- _data/sites.json
- Add airoom.chat as impossible
- Add Pockyt Shop as impossible
- Add VikACG as impossible
> Add airoom.chat, Pockyt Shop and VikACG

- _data/sites.json
- Add Screenshot to Code as hard
- Add HiiCash as impossible
- Add South Plus as impossible
- Add 1Point3Acres as hard
Thanks to Apple, some websites don’t have a account delete button, but if the app’s on the iOS App Store, I can find the account deletion button in the App.
Thanks for the maintenance work!
> Add Screenshot to Code, HiiCash, South Plus, 1Point3Acres

- _data/sites.json
- Add hxcy as impossible
- Add Masiro as impossible
- Add Bangumi as hard
- Add Mikan Project as impossible
> Add hxcy, Masiro, Bangumi and Mikan Project 

- _data/sites.json
The instructions describe an easy and straightforward way to delete the account without contacting support.
The only exceptional case is if the user is banned.
So it's not required to contact customer service to delete any account but only some of them
> Change Myanimelist from Hard to Medium

- _data/sites.json
> Add Leetify.com

- _data/sites.json
* Add The Home Depot México as hard
* Add Office Depot México as impossible
> Add The Home Depot México and Office Depot México

- _data/sites.json
TIDAL changed their account deletion process.
> Update TIDAL to medium

- _data/sites.json
> Update Examine entry with email address

- _data/sites.json
> Add UnKnoWnCheaTs as limited

- _data/sites.json
Forgot to note down all steps during my own account deletion but finding the request button is not difficult. Not sure what their criteria is during the "review" process.
> Add OnePlus

- _data/sites.json
> Update MLH and Prusa

- _data/sites.json
Added information about Certiport.com, an exam and certification website. Note that I have not tested the effects of account deletion on certificates.
> Add Certiport

- _data/sites.json
Added shopper+, floorplanner, cardcastle. Fixed order issue.
> added shopper+, floorplanner, cardcastle

- _data/sites.json
* Add Biletyna
* Add Leave Me Alone
* Update sites.json
> Add Biletyna and Leave Me Alone as easy

- _data/sites.json
Asking for the data package, then use this tool: https://github.com/ishnz/bulk_deletion_helper and finally submitting a GPDR request to discord's privacy support.
> Added a way for discord messages deletion

- _data/sites.json
> Add Holland and Barrett as easy, grafana as hard

- _data/sites.json
> Add Quotev as medium, Sofascore as easy

- _data/sites.json
I sent an email to their support (support@outlier.ai) and requested deletion of my account and I got the following response:
> Thank you for reaching about deleting your account. We respect your decision and want to ensure you fully understand the implications.
> 
> **Please note that you should only proceed with deleting your account if you are certain you no longer wish to use Outlier.**
> 
> Deleting your account won’t resolve any ongoing issues linked to it. Additionally, creating a new account after deletion is not allowed per our Terms of Use & Community Guidelines.
> 
> Since you are unable to delete your account directly, I will assist you with the process. Before we proceed, please carefully consider the following:
> 
> - **Information Reuse:** Once your account is deleted, you …
> Add "Outlier" as Hard

- _data/sites.json
> Update Dynadot to easy

- _data/sites.json
Use latest working URL to data deletion form.
> Fix Ryanair deletion URL

- _data/sites.json
Adds Koofr #2543 to the Just Delete Me website
> Add Koofr as medium

- _data/sites.json
> Add VCV Rack

- _data/sites.json
> Add Onshape

- _data/sites.json
> Added QooApp as Hard

- _data/sites.json
> Add Max For Live as hard

- _data/sites.json
Added Serpstat to sites.json with deletion instructions.
Tested the deletion process and validated JSON syntax.
> Add Serpstat to sites.json as medium.

- _data/sites.json
- Added Autozis to sites.json as easy
- Tested deletion
- Validated json
> Add Autozis to sites.json as easy

- _data/sites.json
Some more sites to add.
Checked validity.
> List of sites to add

- _data/sites.json
https://xdaforums.com/t/closed-how-to-delete-a-xda-developers-account.606901/post-77020948
> Update XDA Developers account-deletion page

- _data/sites.json
If translation added, update the english one for link countries.
Also, cannot link UK, CH, and BE websites because it would override other languages.
Should I add them even though the locales don't exist on the website ? (en-UK, fr-BE, nl-LU, wa, nl-BE, de-CH, fr-CH, it-CH, rm)
> Add La Redoute as hard

- _data/sites.json
You need to send them a message on their website.
Sorry for the multiple pull request.
> Add 17TRACK

- _data/sites.json
3daimtrainer and steelseries is now very easy to delete. 3daimtrainer is now part of steelseries, so the same method applies.
> Update 3daimtrainer and steelseries.

- _data/sites.json
My account was suspended due to a suspicion of residing in Russia, and they refused to delete it until and unless I provided proof of residency outside of Russia, by providing a government-issued ID of another country.
Requests for deletion of suspended accounts go straight to the "risk management department":
```
Hello <name>,
Thank you for contacting the Risk Management department.
It came to our attention that you may reside in the Russian Federation. Due to
the Russian regime's war crimes and human rights violations in Ukraine, we will
no longer be providing services to users registered in Russia. While we
sympathize that this war may not affect your own views or opinion on the
matter, civilians in Ukraine are being bombed, attacked, and murdered by
Russian forces. You may learn more …
```
> Namecheap: change to limited, add note about suspended accounts

- _data/sites.json
First time contributing here, please verify
> Added europathek.de to sites.json

- _data/sites.json
I remember using this long back, but I didn't need my account anymore and saw this website wasn't listed in JDM :)
> Add Padlet.com

- _data/sites.json
Added instant-gaming.com, lingopie.com, spielerplus.de, app.getrecall.ai
> Updated Microsoft, Pixabay, Indeed and added some to sites.json
